### ISSUE TITLE
Support for eventlet

### ISSUE THREAD

**Issue by ItachiSan** [microsoft/debugpy#1048]
I run a Flask application via _gunicorn -k eventlet_ and debug it via _launch.json_.

When doing so, I have these errors:

```
Traceback (most recent call last):
  File "/local/virtualenvs/atropos/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 476, in fire_timers
    timer()
  File "/local/virtualenvs/atropos/lib/python3.10/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/local/virtualenvs/atropos/lib/python3.10/site-packages/eventlet/semaphore.py", line 147, in _do_acquire
    waiter.switch()
greenlet.error: cannot switch to a different thread
```

In the _launch.json_ I can set `"gevent": true` and solve the issues, although I have a small warning that _gevent_ is not installed.

I would like to have a similar option `"eventlet": true`.

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.

**Comment by SeanMooney** [comment]
this is also broken on python 3.12 just an fyi
