### ISSUE TITLE
Last line in pandas dataframe is swallowed in (pytest) debug console

### ISSUE THREAD

**Issue by zljubisic** [microsoft/debugpy#1079]
Type: <b>Bug</b>

Please look at the picture:

![image](https://user-images.githubusercontent.com/67708897/194274965-607aeb22-273c-48de-a01f-e4b4f9cd4aaf.png)

In case you need it:

```
df = pd.DataFrame(
    [
        ['A', 'short text', 1],
        ['A', '1 very 2 very 3 very 4 very 5 very 6 very 7 very 8 very 9 very 10 very text', 2],
        ['A', 'not so long text', 3],
    ], columns=['first', 'description', 'last']
)
df
  first                                        description  last
0     A                                         short text     1
1     A  1 very 2 very 3 very 4 very 5 very 6 very 7 ve...     2
2     A                                   not so long text     3
len(df)
3
df.iloc[-1]
first                         A
description    not so long text
last                          3
Name: 2, dtype: object
pd.options.display.max_colwidth = None
df
  first                                        description  last
0     A                                         short text     1
1     A  1 very 2 very 3 very 4 very 5 very 6 very 7 ve...     2
2     A                                   not so long text     3
df['not existing column']
Traceback (most recent call last):
  File "/home/vagrant/miniconda3/envs/42-proposal-create-a-new-use-case-for-power-savings/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'not existing column'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/miniconda3/envs/42-proposal-create-a-new-use-case-for-power-savings/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/vagrant/miniconda3/envs/42-proposal-create-a-new-use-case-for-power-savings/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'not existing column'
```

Extension version: 2022.14.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

**Comment by karthiknadig** [comment]
@fabioz I can move it into the vscode repo, if this turns out to be a vscode issue.

**Comment by zljubisic** [comment]
Reported problem has happened on my business computer. Now, I have created a new python project on my personal computer in which I have put what I usually put in my business projects (I know it is not the same but on my business computer I cannot provide a log file).

I cannot provoke an error with pandas dataframe, but if I print the same line several times, I get different line spacing. Please look at the picture. I am just pressing up arrow, than enter all the time. Output sometimes has a single blank line, sometimes more than one blank line.


![image](https://user-images.githubusercontent.com/67708897/194410427-6fba613e-fcbc-4aa7-9629-70bc4bf4c7dd.png)


When I experience the error on my business computer, while I am in debug console, how can I collect an environment, settings and everything else that I an compare with debug console environment, settings... on my personal computer?

**Comment by zljubisic** [comment]
Also you can see that nothin is printed after I have passed over print(len(df)) line.

![image](https://user-images.githubusercontent.com/67708897/194413534-2e6151e4-f16c-4a07-a77f-a964b40e6c90.png)

**Comment by zljubisic** [comment]
Furthermore how come that pandas options:
pd.options.display.max_colwidth = None and
pd.options.display.expand_frame_repr = False

doesn't make any difference?
For example if I set max_colwidth to None, no matter how wide the colum is, it should be printed in the full width (you cannot see it, but I have a plenty of room to the right).
Option expand_frame_repr should prevent line breaking dataframe rows.

![image](https://user-images.githubusercontent.com/67708897/194415711-7d81be36-dc92-4795-8626-d65eb5d0d585.png)

**Comment by fabioz** [comment]
> Furthermore how come that pandas options: pd.options.display.max_colwidth = None and pd.options.display.expand_frame_repr = False
> 
> doesn't make any difference? For example if I set max_colwidth to None, no matter how wide the colum is, it should be printed in the full width (you cannot see it, but I have a plenty of room to the right). Option expand_frame_repr should prevent line breaking dataframe rows.

If you set it to `None` then the limits set in through the `PYDEVD_PANDAS_XXX` environment variables become active (see: https://github.com/microsoft/debugpy/issues/1078#issuecomment-1271438410).

**Comment by fabioz** [comment]
@karthiknadig can you move this to VSCode?

I'm confident that the original issue (where the last line of pandas isn't visible) is because VSCode itself is clipping the content, so, it's not fixable in `debugpy` (also, from the description sometimes it's not clipped, but it has different heights even with the same content).

@zljubisic please refer to https://github.com/microsoft/debugpy/issues/1078 (and keep the discussion to that issue) for customization of pandas (as this issue should be moved to the VSCode repo to fix the layout issue in the `Debug Console` where the layout gets clipped sometimes (and other times it has different heights even with the same content).
