### ISSUE TITLE
SyntaxError when restarting debbuging from `launch.json`

### ISSUE THREAD

**Issue by erikscheurer** [microsoft/debugpy#1106]
Hi, I ran into an SyntaxError using the restart debbuging feature when restarting from `launch.json` after having changed something. Instead of debugging the file that I originally was debugging, `launch.json` is executed which obiously leads to a `SyntaxError`.  

## Environment data

- debugpy version: 1.6.3
- OS and version: Fedora 36
- Python version (& distribution if applicable, e.g. Anaconda): 3.10.7
- Using VS Code or Visual Studio: VS Code 1.71.2

## Steps to reproduce:
1. Open a python script, run any command with which you have some time, `print('Hello world')` with a breakpoint worked for me. 
2. Run the debugger with a custom configuration. I just went with the default Python configuration. While the code is running or at a breakpoint continue:
3. Open `launch.json` and change something that changes the launch setup, eg add "args": ["arg1"]
4. Without leaving `launch.json` restart debugging

## Actual behavior

It runs:
```
cd /home/erik/Schreibtisch ; /usr/bin/env /bin/python /home/erik/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 45743 -- /home/erik/Schreibtisch/.vscode/launch.json arg1
```
in the terminal instead of `test.py` in which the breakpoint is set.  This then leads to a syntax error, as `launch.json` isn't a python script:
<details>

```
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/erik/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/erik/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/erik/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/erik/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/erik/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 294, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "/home/erik/Schreibtisch/.vscode/launch.json", line 2
    // Use IntelliSense to learn about possible attributes.
    ^^
SyntaxError: invalid syntax
```

</details>

## Expected  behavior

```
cd /home/erik/Schreibtisch ; /usr/bin/env /bin/python /home/erik/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 36283 -- /home/erik/Schreibtisch/test.py arg1
```
is what I expected, this is also what happens usually, eg when changing a different python file and restarting debugging from there. The error also doesn't occur when just adding a space or something to `launch.json`. 

I don't know if this is an error of debug.py or of VS Code since it is wrong in the console before executing anything, so referral is also appreciated.

**Comment by fabioz** [comment]
Making the launching is not controlled by `debugpy`... @karthiknadig can you move this to `vscode-python`?

**Comment by int19h** [comment]
It sounds like you have `"program": "${file}"` in your launch.json, so it runs whatever you currently have opened in the editor. When restarting debugging, it is the same as stopping a session and starting it again with the same debug configuration - but if that configuration has any variables in it, they get resolved again, so switching the tab changed the target script.
