### ISSUE TITLE
Error when trying to attach to PID in Docker container on Apple Silicon

### ISSUE THREAD

**Issue by AaronBeaudoin** [microsoft/debugpy#1113]
When attempting to attach to a PID inside a Docker container on Apple Silicon (ARM), I get the following output:

```
odoo@dabeea5fb5e3:/debug/debugpy$ python3 /debug/debugpy --listen 0.0.0.0:5678 --pid 73943
Unable to attach to process in arch: aarch64 (did not find attach_aarch64.so in /debug/debugpy/_vendored/pydevd/pydevd_attach_to_process).
E+00000.007: Code injection into PID=73943 failed:
             
             Traceback (most recent call last):
               File "/debug/debugpy/../debugpy/server/cli.py", line 409, in attach_to_pid
                 show_debug_info=int(os.getenv("DEBUGPY_ATTACH_BY_PID_DEBUG_INFO", "0")),
               File "/debug/debugpy/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 395, in run_python_code_linux
                 raise RuntimeError('Could not find .so for attach to process.')
             RuntimeError: Could not find .so for attach to process.
             
             Stack where logged:
               File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
                 "__main__", mod_spec)
               File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
                 exec(code, run_globals)
               File "/debug/debugpy/__main__.py", line 45, in <module>
                 cli.main()
               File "/debug/debugpy/../debugpy/server/cli.py", line 444, in main
                 run()
               File "/debug/debugpy/../debugpy/server/cli.py", line 412, in attach_to_pid
                 log.reraise_exception("Code injection into PID={0} failed:", pid)
               File "/debug/debugpy/../debugpy/common/log.py", line 226, in reraise_exception
                 _exception(format_string, *args, **kwargs)
             

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/debug/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/debug/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/debug/debugpy/../debugpy/server/cli.py", line 412, in attach_to_pid
    log.reraise_exception("Code injection into PID={0} failed:", pid)
  File "/debug/debugpy/../debugpy/server/cli.py", line 409, in attach_to_pid
    show_debug_info=int(os.getenv("DEBUGPY_ATTACH_BY_PID_DEBUG_INFO", "0")),
  File "/debug/debugpy/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 395, in run_python_code_linux
    raise RuntimeError('Could not find .so for attach to process.')
RuntimeError: Could not find .so for attach to process.
```

## Environment

```
debugpy: v1.5.1
Host OS: macOS v12.5
Docker: v20.10.17
Python: v3.7.3
VS Code: N/A
```

## Actual Behavior

See description.

## Expected Behavior

The command injects a debugger into the process as described in the README.

## Steps to Reproduce

1. Start a Python Docker container on an ARM Apple Silicon computer.
2. Run `docker inspect -f '{{ .State.Pid }}' <container_id>` to get the process PID.
3. Run `docker exec -it <container_id> python3 -m debugpy --listen 0.0.0.0:5678 --pid <pid>`.

**Comment by AaronBeaudoin** [comment]
Also, I am able to launch the process with `debugpy` with no issues, so I'm not sure why attaching doesn't work too.
