### ISSUE TITLE
Python debugger does not attach to Azure function

### ISSUE THREAD

**Issue by Rashair** [microsoft/debugpy#1118]
Type: <b>Bug</b>

1. Start new python azure function with debugger.
2. Close the function.
3. Restart the debugger.

Function will start but the debugger will not be attached even when trying multiple times.
No errors visible.
When the source code is changed, there'll be an error and function will crash:
```
 Executing <Task pending name='Task-1' coro=<start_async() running at C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\main.py:61> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000025405F19AD0>()] created at C:\pyenv\pyenv-win\versions\3.9.13\lib\asyncio\base_events.py:429> cb=[_run_until_complete_cb() at C:\pyenv\pyenv-win\versions\3.9.13\lib\asyncio\base_events.py:184] created at C:\pyenv\pyenv-win\versions\3.9.13\lib\asyncio\base_events.py:626> took 0.188 seconds
[2022-11-09T18:15:35.089Z] Worker process started and initialized.
[2022-11-09T18:15:38.243Z] Host lock lease acquired by instance ID '00000000000000000000000047E6F347'.
[2022-11-09T18:15:40.040Z] Traceback (most recent call last):
[2022-11-09T18:15:40.041Z]   File "C:\pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 197, in _run_module_as_main
[2022-11-09T18:15:40.043Z]     return _run_code(code, main_globals, None,
[2022-11-09T18:15:40.043Z]   File "C:\pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 87, in _run_code
[2022-11-09T18:15:40.044Z]     exec(code, run_globals)
[2022-11-09T18:15:40.045Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
[2022-11-09T18:15:40.046Z]     cli.main()
[2022-11-09T18:15:40.047Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
[2022-11-09T18:15:40.048Z]     run()
[2022-11-09T18:15:40.049Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 268, in run_file
[2022-11-09T18:15:40.049Z]     start_debugging(target)
[2022-11-09T18:15:40.050Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 256, in start_debugging
[2022-11-09T18:15:40.051Z]     debugpy.listen(options.address)
[2022-11-09T18:15:40.052Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\public_api.py", line 31, in wrapper
[2022-11-09T18:15:40.053Z]     return wrapped(*args, **kwargs)
[2022-11-09T18:15:40.054Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 140, in debug
[2022-11-09T18:15:40.055Z]     log.reraise_exception("{0}() failed:", func.__name__, level="info")
[2022-11-09T18:15:40.056Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 138, in debug
[2022-11-09T18:15:40.057Z]     return func(address, settrace_kwargs, **kwargs)
[2022-11-09T18:15:40.058Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 240, in listen
[2022-11-09T18:15:40.059Z]     raise RuntimeError(str(endpoints["error"]))
[2022-11-09T18:15:40.059Z] RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
[2022-11-09T18:15:40.077Z] Language Worker Process exited. Pid=35312.
[2022-11-09T18:15:40.078Z] C:\pyenv\pyenv-win\shims\python3.9.bat exited with code 1 (0x1).     log.reraise_exception("{0}() failed:", func.__name__, level="info"),    raise RuntimeError(str(endpoints["error"])),RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted.
[2022-11-09T18:15:40.093Z] Failed to start a new language worker for runtime: python.
[2022-11-09T18:15:40.094Z] System.Private.CoreLib: A task was canceled.
[2022-11-09T18:15:40.728Z] Traceback (most recent call last):
[2022-11-09T18:15:40.729Z]   File "C:\pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 197, in _run_module_as_main
[2022-11-09T18:15:40.730Z]     return _run_code(code, main_globals, None,
[2022-11-09T18:15:40.731Z]   File "C:\pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 87, in _run_code
[2022-11-09T18:15:40.732Z]     exec(code, run_globals)
[2022-11-09T18:15:40.733Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
[2022-11-09T18:15:40.734Z]     cli.main()
[2022-11-09T18:15:40.735Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
[2022-11-09T18:15:40.735Z]     run()
[2022-11-09T18:15:40.736Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 268, in run_file
[2022-11-09T18:15:40.737Z]     start_debugging(target)
[2022-11-09T18:15:40.737Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 256, in start_debugging
[2022-11-09T18:15:40.738Z]     debugpy.listen(options.address)
[2022-11-09T18:15:40.739Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\public_api.py", line 31, in wrapper
[2022-11-09T18:15:40.740Z]     return wrapped(*args, **kwargs)
[2022-11-09T18:15:40.741Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 140, in debug
[2022-11-09T18:15:40.741Z]     log.reraise_exception("{0}() failed:", func.__name__, level="info")
[2022-11-09T18:15:40.742Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 138, in debug
[2022-11-09T18:15:40.743Z]     return func(address, settrace_kwargs, **kwargs)
[2022-11-09T18:15:40.744Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 240, in listen
[2022-11-09T18:15:40.745Z]     raise RuntimeError(str(endpoints["error"]))
[2022-11-09T18:15:40.745Z] RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
[2022-11-09T18:15:40.768Z] Language Worker Process exited. Pid=50196.
[2022-11-09T18:15:40.769Z] C:\pyenv\pyenv-win\shims\python3.9.bat exited with code 1 (0x1).     log.reraise_exception("{0}() failed:", func.__name__, level="info"),    raise RuntimeError(str(endpoints["error"])),RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted.
[2022-11-09T18:15:44.419Z] Host lock lease acquired by instance ID '00000000000000000000000047E6F347'.
[2022-11-09T18:15:51.421Z] Traceback (most recent call last):
[2022-11-09T18:15:51.422Z]   File "C:\pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 197, in _run_module_as_main
[2022-11-09T18:15:51.423Z]     return _run_code(code, main_globals, None,
[2022-11-09T18:15:51.423Z]   File "C:\pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 87, in _run_code
[2022-11-09T18:15:51.424Z]     exec(code, run_globals)
[2022-11-09T18:15:51.424Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
[2022-11-09T18:15:51.425Z]     cli.main()
[2022-11-09T18:15:51.426Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
[2022-11-09T18:15:51.426Z]     run()
[2022-11-09T18:15:51.427Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 268, in run_file
[2022-11-09T18:15:51.428Z]     start_debugging(target)
[2022-11-09T18:15:51.428Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 256, in start_debugging
[2022-11-09T18:15:51.429Z]     debugpy.listen(options.address)
[2022-11-09T18:15:51.430Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\public_api.py", line 31, in wrapper
[2022-11-09T18:15:51.430Z]     return wrapped(*args, **kwargs)
[2022-11-09T18:15:51.431Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 140, in debug
[2022-11-09T18:15:51.432Z]     log.reraise_exception("{0}() failed:", func.__name__, level="info")
[2022-11-09T18:15:51.432Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 138, in debug
[2022-11-09T18:15:51.433Z]     return func(address, settrace_kwargs, **kwargs)
[2022-11-09T18:15:51.433Z]   File "c:\Users\przem\.vscode\extensions\ms-python.python-2022.17.13051012\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py", line 240, in listen
[2022-11-09T18:15:51.434Z]     raise RuntimeError(str(endpoints["error"]))
[2022-11-09T18:15:51.435Z] RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
[2022-11-09T18:15:51.455Z] Language Worker Process exited. Pid=27996.
[2022-11-09T18:15:51.456Z] C:\pyenv\pyenv-win\shims\python3.9.bat exited with code 1 (0x1).     log.reraise_exception("{0}() failed:", func.__name__, level="info"),    raise RuntimeError(str(endpoints["error"])),RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted.
[2022-11-09T18:15:51.457Z] Exceeded language worker restart retry count for runtime:python. Shutting down and proactively recycling the Functions Host to recover
```

The problem persists both on 1.73 and 1.72 vscode versions.
It also persist with Preview and Stable version ofthe extension.

Extension version: 2022.16.1
VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (46.02GB free)|
|Process Argv|D:\\Source\\the-cognity\\perfect-emotion-service --crash-reporter-id fa0fb12d-6884-422d-8c98-ca5d06daf94f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30605430
3d0df643:30604793
dbltrim-noruby:30604474

```

</details>

**Comment by Rashair** [comment]
Sorry, but that's a different problem, in my issue, the debugger doesn't attach at all.
I thought the error was connected, that's why I posted it.
Even if I don't save the file, the debugger won't show up. 
I also can't attach the process via PID, because it gives `connection refused` error (which doesn't show up with normal run)

**Comment by Rashair** [comment]
After some tests, I can attach the debugger when I first start it from a freshly created function (**A**), but not when I start it from the one I want to work with (**B**).
If I start the debugger from the A first and then for B, it does seem to attach and work (2 different debugging ports).

**Comment by int19h** [comment]
You mentioned that it wasn't doing that until recently - do you recall how long ago you first saw it break? I wonder if this is due to changes on Azure Function side, since we haven't shipped a new debugpy release for a while.

**Comment by Rashair** [comment]
I've noticed it around Monday evening - 07.11

**Comment by int19h** [comment]
Can you describe in more detail how you  set up this debug session? i.e. the launch.json config used, and any other things that you might be doing in command line in addition to starting the session in VSCode (if any).

**Comment by Rashair** [comment]
I'm not sure why, but it started working again🤷🏻‍♂️ - it attaches every time I try. Maybe it was really the extension problem in the first place?
My setup is pretty standard:

**VsCode:**

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Python Functions",
            "type": "python",
            "request": "attach",
            "port": 9091,
            "preLaunchTask": "func: host start",
            "justMyCode": true,
        }
    ]
}
```

tasks.json:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "func",
			"command": "host start",
			"problemMatcher": "$func-python-watch",
			"isBackground": true,
			"dependsOn": "pip install (functions)"
		},
		{
			"label": "pip install (functions)",
			"type": "shell",
			"osx": {
				"command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
			},
			"windows": {
				"command": "${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
			},
			"linux": {
				"command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
			},
			"problemMatcher": []
		}
	]
}

**Az Func:**
host.json:
```
{
  "version": "2.0",
  "logging": {},
  "extensions": {},
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  }
}
```


local.settings.json
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:11000/devstoreaccount1;",
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "PYTHON_ENABLE_WORKER_EXTENSIONS": "true"
  },
  "HOST": {
    "LocalHttpPort": 40041
  }
}
```
