### ISSUE TITLE
No module named 'loguru'

### ISSUE THREAD

**Issue by ultramen6** [microsoft/debugpy#1145]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.4
- OS and version: Manjaro Linux
- Python version (& distribution if applicable, e.g. Anaconda): 3.10.8
- Using VS Code or Visual Studio: Using Astrovim with manson.nvim installer

***My structure***

**python_test.py**

```
import loguru
import sys
print('\n'.join(sorted(sys.path)))

print(loguru)
```

## Actual behavior

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ultra/.local/share/nvim/mason/packages/debugpy/venv/lib/python3.10/site-packages/debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/ultra/.local/share/nvim/mason/packages/debugpy/venv/lib/python3.10/site-packages/debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/ultra/.local/share/nvim/mason/packages/debugpy/venv/lib/python3.10/site-packages/debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/ultra/.local/share/nvim/mason/packages/debugpy/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/ultra/.local/share/nvim/mason/packages/debugpy/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ultra/.local/share/nvim/mason/packages/debugpy/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/ultra/code/the_game1/tests/test.py", line 1, in <module>
    import loguru
ModuleNotFoundError: No module named 'loguru'
```

## Expected  behavior

Debug session starts fine

if i run this file in console without debugger:

```
 ~ python python_test.py 
/home/ultra
/home/ultra/code/the_game1/env/lib/python3.10/site-packages
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/lib/python310.zip
<module 'loguru' from '/home/ultra/code/the_game1/env/lib/python3.10/site-packages/loguru/__init__.py'>
```

## Steps to reproduce:
in console:

`python3.10 test.py `
![Снимок экрана от 2022-12-08 01-50-10](https://user-images.githubusercontent.com/77591400/206313824-392774c6-2868-456c-ae8d-fe37a8dcbd3b.png)
![Снимок экрана от 2022-12-08 01-50-02](https://user-images.githubusercontent.com/77591400/206313829-febf7ce1-914c-4813-893f-163bec38d355.png)

**Comment by ultramen6** [comment]
This problem only occurs with loguru. On other packages, the debugger does not swear

**Comment by int19h** [comment]
You need to make sure that you're running your app in the properly activated virtual environment to access packages that are installed in that environment (`the_game1/env`).

I'm not familiar enough with Astrovim debugpy integration to say how this is achieved - it's not something that debugpy itself does, it just assumes that the client will take care of that. The first thing that I would try is activating the environment manually and then starting Vim from that prompt.

**Comment by ultramen6** [comment]
now everything works as it should. thanks a lot!
