### ISSUE TITLE
Debug crashes when running a Python2 subprocess

### ISSUE THREAD

**Issue by abrahammurciano** [microsoft/debugpy#1193]
## Environment data

- debugpy version: 1.6.5
- OS and version: Ubuntu 18.04
- Python version: 3.11.0
- Using VS Code

## Actual behavior

When debugging a python script that starts a python2 subprocess, the subprocess crashes.

## Expected  behavior

The subprocess should behave the same way as when the python script is run outside the debugger.

## Steps to reproduce:
Run this `hello_world.py` file with the VS Code debugger (e.g. F5 > Python File)
```py
from subprocess import run
run(["/usr/bin/python2", "-c", "print('hello world')"])
```
That opens the terminal and runs this command with the following output.
```
❯  cd /homes/abrahamm/playground/python ; /usr/bin/env /homes/abrahamm/playground/python/.venv/bin/python /homes/abrahamm/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 60427 -- /homes/abrahamm/playground/python/hello_world.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/homes/abrahamm/.vscode/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 3244
    def log_to(log_file:str, log_level=3) -> None:
                       ^
SyntaxError: invalid syntax
```

However when running without the debugger, it works just fine.
```
❯ python ./hello_world.py
hello world
```

Additionally, if the `subprocess.run` call has the argument `shell=True` it also works fine.

It seems that the debugger is hijacking python child processes to wrap some code before it starts, and that code is python3 syntax but it is running with the python2 interpreter provided to the subprocess. (Since shell=True starts a shell subprocess which in turn starts the python2 subprocess it seems that is not hijacked by the debugger)

**Comment by int19h** [comment]
This can be made to work for this particular case, when `python2` is the name of the subprocess binary, although it would require pydevd changes to make this customizable.

However, in the more general case, the subprocess might be trying to run `python` (or `python.exe` on Windows), and we don't know which version it might be, so we have to speculatively hijack. The only way I can see this working is if the corresponding codepath in debugpy starts with code that is Python 2 compatible, and bails early if it detects that it's running on py2.

**Comment by int19h** [comment]
In the meantime, you can disable the subprocess hijacking behavior in general by setting `"subProcess": false` in your launch.json. Unfortunately, that will also prevent debugging Python 3 subprocesses, if you have any.
