### ISSUE TITLE
pydevd complaining about `attach_x86_64.dylib` on macOS on ARM

### ISSUE THREAD

**Issue by aadan-benchsci** [microsoft/debugpy#1209]
Debugpy doesn't seem to start on mac os 13.2 The only thing that I can see in the logs is the following section 
```
2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib lib in arch: arm64.
0.00s - Error loading: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib
Traceback (most recent call last):
  File "/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_tracing.py", line 263, in _load_python_helper_lib_uncached
    lib = ctypes.pydll.LoadLibrary(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
``` 
A longer log is below

## Environment data

- debugpy version: 1.6.6
- OS and version: Mac Osx Arm64 M1 pro, 13.2 OS
- Python version (& distribution if applicable, e.g. Anaconda):pyenv python 3.11

## Actual behaviour
Debuger never launches 

## Expected  behaviour 
Debugger should launch as expected

## Steps to reproduce:
```
pip install debugpy
python -m debugpy  --listen 0.0.0.0:5678 --log-to logs test_python.py
```

```
0.09s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py - _read_line
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py - _on_run
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py - run
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap_inner
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - wait
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/queue.py - get
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py - _on_run
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py - run
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap_inner
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - set_tracing_for_untraced_contexts
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - on_breakpoints_changed
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - clear_dont_trace_start_end_patterns_caches
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_api.py - set_dont_trace_start_end_patterns
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - _locked_settrace
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - settrace
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - _settrace
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - connect
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - debug
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/public_api.py - wrapper
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - start_debugging
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - run_file
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - main
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py - <module>
0.00s - Set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/runpy.py - _run_code
0.00s - Set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/runpy.py - _run_module_as_main
0.00s - Using /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib lib in arch: arm64.
0.00s - Error loading: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib
Traceback (most recent call last):
  File "/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_tracing.py", line 263, in _load_python_helper_lib_uncached
    lib = ctypes.pydll.LoadLibrary(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib, 0x0006): tried: '/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib' (no such file), '/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - wait
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - wait
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - _on_run
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py - run
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap_inner
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - wait
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - wait
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - _on_run
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py - run
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap_inner
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py - _read_line
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py - _on_run
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py - run
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap_inner
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - wait
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/queue.py - get
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py - _on_run
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py - run
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap_inner
0.00s - SKIP set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/threading.py - _bootstrap
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - set_tracing_for_untraced_contexts
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - _locked_settrace
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - settrace
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - _settrace
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - connect
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - debug
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/public_api.py - wrapper
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - start_debugging
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - run_file
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - main
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py - <module>
0.00s - Set tracing of frame: /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/runpy.py - _run_module_as_main
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py - settrace
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - _settrace
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - connect
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py - debug
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/public_api.py - wrapper
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - start_debugging
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - run_file
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py - main
0.00s - SKIP set tracing of frame: /Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py - <module>
0.00s - File not traced (not in project - force_check_project_scope): /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/genericpath.py
0.00s - File not traced (not in project - force_check_project_scope): /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/posixpath.py
0.00s - File not traced (not in project - force_check_project_scope): /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/site.py
0.00s - File not traced (not in project - force_check_project_scope): /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/sysconfig.py
0.00s - File not traced (not in project - force_check_project_scope): /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/os.py
0.00s - File not traced (not in project - force_check_project_scope): /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/pkgutil.py
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - File not traced (not in project - force_check_project_scope): /Users/aadan/.local/share/pyenv/versions/3.11-dev/lib/python3.11/runpy.py
0.00s - sending cmd (http_json) -->      CMD_THREAD_KILL {"type": "event", "event": "thread", "body": {"reason": "exited", "threadId": 1}, "seq": 28, "pydevd_cmd_id": 104}

0.02s - Process ThreadsRequest: {
    "command": "threads",
    "seq": 11,
    "type": "request"
}

0.00s - sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 11, "success": true, "command": "threads", "body": {"threads": []}, "seq": 30, "pydevd_cmd_id": 502}

0.27s - No threads alive, finishing debug session
0.00s - PyDB.dispose_and_kill_all_pydevd_threads (called from: File "/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 269, in _on_run)
0.00s - PyDB.dispose_and_kill_all_pydevd_threads (first call)
0.00s - PyDB.dispose_and_kill_all_pydevd_threads no commands being processed.
0.00s - PyDB.dispose_and_kill_all_pydevd_threads (called from: File "/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1777, in process_internal_commands)
0.00s - PyDB.dispose_and_kill_all_pydevd_threads (already disposed - wait)
0.00s - PyDB.dispose_and_kill_all_pydevd_threads waiting for pydb daemon threads to finish
0.00s - PyDB.dispose_and_kill_all_pydevd_threads killing thread: <ReaderThread(pydevd.Reader, started daemon 6190149632)>
0.00s - pydevd.Reader received kill signal
0.00s - PyDB.dispose_and_kill_all_pydevd_threads killing thread: <WriterThread(pydevd.Writer, started daemon 6173323264)>
0.00s - sending cmd (http_json) -->             CMD_EXIT {"type": "event", "event": "terminated", "seq": 32, "body": {}, "pydevd_cmd_id": 129}

0.00s - pydevd.Writer received kill signal
0.00s - PyDB.dispose_and_kill_all_pydevd_threads killing thread: <PyDBCommandThread(pydevd.CommandThread, started daemon 6206976000)>
0.00s - pydevd.CommandThread received kill signal
0.00s - PyDB.dispose_and_kill_all_pydevd_threads killing thread: <CheckAliveThread(pydevd.CheckAliveThread, started 6223802368)>
0.00s - pydevd.CheckAliveThread received kill signal
0.00s - WriterThread: CMD_EXIT received
0.00s - WriterThread: exit
0.00s - ReaderThread: empty contents received (len(line) == 0).
0.00s - PyDB.dispose_and_kill_all_pydevd_threads (called from: File "/Users/aadan/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 301, in _terminate_on_socket_close)
0.00s - PyDB.dispose_and_kill_all_pydevd_threads (already disposed - wait)
0.50s - PyDB.dispose_and_kill_all_pydevd_threads: finished
0.00s - PyDB.dispose_and_kill_all_pydevd_threads: finished
0.00s - ReaderThread: exit
0.00s - pydevd.stoptrace()
```
comes from [1192](https://github.com/microsoft/debugpy/issues/1192)

**Comment by int19h** [comment]
The message in the logs is expected on ARM currently, but it shouldn't prevent the debugger from running - indeed, the log keeps going, and it looks like it successfully connected to the adapter, at the very least.  Can you clarify what you mean by "debugger never launches"?

**Comment by judej** [comment]
will complete this as part of #1220
