### ISSUE TITLE
Error attaching Python debugger with debugpy: 'Could not find .so for attach to process' on macbook m1

### ISSUE THREAD

**Issue by nkdanta1** [microsoft/debugpy#1220]
I'm trying to attach a Python debugger to a process using the debugpy module, but I'm getting the following error:

```
Unable to attach to process in arch: aarch64 (did not find attach_aarch64.so in /usr/local/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process).
E+00000.011: Code injection into PID=7 failed:
             Traceback (most recent call last):
               File "/usr/local/lib/python3.8/site-packages/debugpy/server/cli.py", line 391, in attach_to_pid
                 add_code_to_python_process.run_python_code(
               File "/usr/local/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 400, in run_python_code_linux
                 raise RuntimeError('Could not find .so for attach to process.')
             RuntimeError: Could not find .so for attach to process.
```
The command I'm running is:
`python3 -m debugpy --listen 0.0.0.0:5678 --pid 7`

I'm not sure what could be causing this error or how to fix it. Any help would be greatly appreciated.

# Environment
debugpy: v1.6.6
Host OS:  Ventura 13.1
Docker: v23.0.1
Python: v3.8.12

# Actual Behavior
See description

# Expected Behavior
The command injects a debugger into the process.

# Steps to Reproduce
1. Start a Python Docker container on an ARM Apple Silicon computer.
2. Run `python3 -m debugpy --listen 0.0.0.0:5678 --pid <pid>` inside container.

**Comment by int19h** [comment]
Attach-to-PID is not supported on ARM.

https://github.com/microsoft/debugpy/issues/286 is the item tracking this for Linux, but I think we should have a separate one on macOS, as there may be differences in implementation.

**Comment by nkdanta1** [comment]
thanks @int19h for the faster response. Is there any workaround for ARM currently?

**Comment by int19h** [comment]
If you can run arbitrary Python code in the target process, or can edit the code that runs normally, you can use attach-to-TCP via `import debugpy` etc.

**Comment by nkdanta1** [comment]
looking forward to this enhancement. Is there any timeline for thsi fix?

**Comment by nkdanta1** [comment]
Hi @int19h, is there any news on this enhancement?

**Comment by sevetseh28** [comment]
I'm having a similar issue on a Macbook Pro with the M2 Pro chip (ARM64). 
I'm developing in a devcontainer with Ubuntu 22.04 and I get:

```
--- Starting attach to pid: 25047 ---
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000ffff874de844 in __GI___select (nfds=nfds@entry=0, readfds=readfds@entry=0x0, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0xffffdadd73d8) at ../sysdeps/unix/sysv/linux/select.c:69
69	../sysdeps/unix/sysv/linux/select.c: No such file or directory.
warning: File "/root/.pyenv/versions/3.9.18/bin/python3.9-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /root/.pyenv/versions/3.9.18/bin/python3.9-gdb.py
line to your configuration file "/root/.config/gdb/gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
**The target architecture is set to "auto" (currently "aarch64").**
.....
<skipped for brevity>
.....

subprocess.CalledProcessError: Command 'gdb --nw --nh --nx --pid 25047 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture auto' --eval-command='call (void*)dlopen("/root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='sharedlibrary attach_linux_amd64' --eval-command='call (int)DoAttach(0, "import codecs;import json;import sys;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0] if s is not None else None;script_dir = decode([4....
```

So in my case, it's trying to use `attach_linux_amd64.so` which is wrong.
I'd love to see this prioritised now that Apple is about to release the third generation of Silicon chips, attaching to running process is, in my view, a basic debugging use case. I have many programs that launch a subprocess to which I need to attach in order to continue debugging.

**Comment by int19h** [comment]
@sevetseh28, can you clarify the scenario? We generally assume that TCP attach is the default scenario since it's more reliable (Python runtime really isn't designed this kind of thing, so the way this has to be implemented is incredibly hacky). You shouldn't need to do any code changes so long as you control the launch - debugpy CLI should cover all cases. Attaching by PID is really mostly meant for Python embedded in some host process. But if there's another scenario where debugpy CLI is not an option, it would help prioritize this higher.

**Comment by sevetseh28** [comment]
> @sevetseh28, can you clarify the scenario? We generally assume that TCP attach is the default scenario since it's more reliable (Python runtime really isn't designed for this kind of thing, so the way it has to be implemented is incredibly hacky). You shouldn't need to do any code changes so long as you control the launch - debugpy CLI should cover all cases. Attaching by PID is really mostly meant for Python embedded in some host process. But if there's another scenario where debugpy CLI is not an option, it would help prioritize this higher.

Yes, my usecase involves debugging inside a devcontainer using VSCode. 

In order to do that I'm using the official Python extension for VSCode which seems to use `debugpy` behding the scenes.
`debugpy` is not actually installed in my program's virtualenv but used by VSCode's Python extension.

My main Python program creates other processes (`subprocess.Popen`) which also run Python code.
These child processes are the processes that I need to debug by attaching to their PIDs.

If I want to use `debugpy` over TCP I first need to install it in my virtualenv, and then write this in my code:
```python
import debugpy
# Enable the debugger to listen on port 5678
debugpy.listen(('0.0.0.0', 5678))
# Pause execution until debugger is attached
debugpy.wait_for_client()
```

Thanks!

**Comment by int19h** [comment]
So long as you start the main process using `python -m debugpy ...`, or use the "launch" debug configuration from VSCode, the child processes should be automatically connected to in this scenario, unless you have `"subProcess": false` in your config. If it doesn't auto-attach to the children in this setup, that would be a bug in its own right.

**Comment by sevetseh28** [comment]
> So long as you start the main process using `python -m debugpy ...`, or use the "launch" debug configuration from VSCode, the child processes should be automatically connected to in this scenario, unless you have `"subProcess": false` in your config. If it doesn't auto-attach to the children in this setup, that would be a bug in its own right.

I actually had tried that. I have a launch configuration for the main process with `subProcess: true` but for some reason is not auto-attaching to the subprocess. Where do you think the issue lies in that case?
I can see the command VSCode is running is this one:

```
python/debugpy/adapter/../../debugpy/launcher 36129 -- /app/checker/debug_wrapper.py --verbose --daemon 
2023-08-29 12:19:51.399 [info] DAP Server launched with command: /app/virtualenv/env3/bin/python /root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter
2023-08-29 12:19:51.518 [info] Send text to terminal:  cd /app/checker ; /usr/bin/env /app/virtualenv/env3/bin/python /root/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 58935 -- /app/checker/debug_wrapper.py --verbose --daemon 
```

**Comment by greenatatlassian** [comment]
So, it seems there is already a solution to this problem, but for some reason it is only in the [IntelliJ fork of PyDev](https://github.com/JetBrains/intellij-community/blob/master/python/helpers/pydev/pydevd_attach_to_process/linux_and_mac/compile_linux_aarch64.sh) Not sure why it wasn't contributed [upstream](https://github.com/fabioz/PyDev.Debugger/), nor why this issue hasn't been raised upstream. 

I've raised this upstream: https://github.com/fabioz/PyDev.Debugger/issues/277

**Comment by ipatch** [comment]
https://github.com/microsoft/debugpy/issues/286#issuecomment-3447930290

**Comment by mechaturtles** [comment]
Seems to have been addressed by #1917 (TL;DR adding arm64 macs as a build target for process attach)

@greenatatlassian seems this change may have been pushed upstream in pydev not too long after so I dropped a comment to your issue
