### ISSUE TITLE
Python Debugger stops in first few seconds without output

### ISSUE THREAD

**Issue by GlenDC** [microsoft/debugpy#1283]

**Comment by int19h** [comment]
The one difference between Intel and ARM Macs would be that the latter don't get the optimized native-code debugger bits. However, pure Python debugger is generally *more* stable (but slower), so it is surprising to see it crash if that is what's happening here.

Try setting `"logToFile": true` and have a look at `debugpy*.log` files in your extension install folder - this might offer some clues.

**Comment by GlenDC** [comment]
```
I+00000.024: /handling #1 request "launch" from Adapter/
             Failed to set up process group
             
             Traceback (most recent call last):
               File "/Users/me/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/launcher/debuggee.py", line 74, in preexec_fn
                 tty = os.open("/dev/tty", os.O_RDWR)
             OSError: [Errno 6] Device not configured: '/dev/tty'
             
             Stack where logged:
               File "/Users/me/.pyenv/versions/3.10.3/lib/python3.10/threading.py", line 966, in _bootstrap
                 self._bootstrap_inner()
               File "/Users/me/.pyenv/versions/3.10.3/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
                 self.run()
               File "/Users/me/.pyenv/versions/3.10.3/lib/python3.10/threading.py", line 946, in run
                 self._target(*self._args, **self._kwargs)
               File "/Users/me/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/messaging.py", line 1458, in _run_handlers
                 handler()
               File "/Users/me/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/messaging.py", line 701, in _handle
                 result = handler(self)
               File "/Users/me/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/launcher/handlers.py", line 140, in launch_request
                 debuggee.spawn(process_name, cmdline, env, redirect_output)
               File "/Users/me/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/launcher/debuggee.py", line 91, in spawn
                 process = subprocess.Popen(cmdline, env=env, bufsize=0, **kwargs)
               File "/Users/me/.pyenv/versions/3.10.3/lib/python3.10/subprocess.py", line 966, in __init__
                 self._execute_child(args, executable, preexec_fn, close_fds,
               File "/Users/me/.pyenv/versions/3.10.3/lib/python3.10/subprocess.py", line 1775, in _execute_child
                 self.pid = _posixsubprocess.fork_exec(
               File "/Users/me/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/launcher/debuggee.py", line 83, in preexec_fn
                 log.swallow_exception(
               File "/Users/me/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
```

Is the only error-ihsh output I can find, this one I find in `debugpy.launcher-xxx.log`.

**Comment by int19h** [comment]
This one indicates running outside of a terminal, but this is expected for "internalConsole", and is not actually an error.

`debugpy.pydevd*.log` is logged from the debuggee and might be more informative. At the very least, if it suddenly stops logging, it would be interesting to see what happened right before then.

**Comment by GlenDC** [comment]
I see.

This is the last couple of lines of such a session:

```
0.00s - File not traced (not in project - force_check_project_scope): /Users/<me>/.pyenv/versions/3.10.3/lib/python3.10/_strptime.py
0.00s - File not traced (not in project - force_check_project_scope): /Users/<me>/.pyenv/versions/3.10.3/lib/python3.10/calendar.py
0.00s - File not traced (not in project - force_check_project_scope): /Users/<me>/.pyenv/versions/3.10.3/lib/python3.10/random.py
0.00s - Patching args: ['gcloud', 'config', 'config-helper', '--format', 'json']
0.00s - Process is not python, returning.
1.02s - Patching args: ['gcloud', 'config', 'config-helper', '--format', 'json']
0.00s - Process is not python, returning.
0.67s - File not traced (not in project - force_check_project_scope): /Users/<me>/.pyenv/versions/3.10.3/envs/crawlers/lib/python3.10/site-packages/grpc/_plugin_wrapping.py
0.19s - sending cmd (http_json) -->    CMD_THREAD_CREATE {"type": "event", "event": "thread", "body": {"reason": "started", "threadId": 3}, "seq": 32, "pydevd_cmd_id": 103}

0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.00s - Unable to load helper lib to set tracing to all threads (unsupported python vm).
0.11s - Process ThreadsRequest: {
    "command": "threads",
    "seq": 12,
    "type": "request"
}

0.00s - sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 12, "success": true, "command": "threads", "body": {"threads": [{"id": 1, "name": "MainThread"}, {"id": 2, "name": "Thread-6 (refresh_data_sources)"}, {"id": 3, "name": "Thread-7 (_run)"}]}, "seq": 34, "pydevd_cmd_id": 502}

0.08s - sending cmd (http_json) -->      CMD_THREAD_KILL {"type": "event", "event": "thread", "body": {"reason": "exited", "threadId": 3}, "seq": 36, "pydevd_cmd_id": 104}

0.08s - File traced: /Users/<my_library>/Middleware/authentication/client_based_authentication_middleware.py
0.00s - File traced: /Users/<my_library>/Middleware/authentication/authentication_middleware.py
```

Don't think that really helps? Was thinking `Unable to load helper lib to set tracing to all threads (unsupported python vm).` but that's all over the logs in that file so not sure that is something unexpected?

I feel the answer is obvious if we know why it's exiting though, should it not just tell that somewhere, why? Even if some kind of stack trace or obscure dump?

**Comment by int19h** [comment]
If it were exiting cleanly then yes, this should be visible in the logs. The fact that the log is cut abruptly like that generally implies a hard crash, not even on Python level but something like a segfault.

I'm not too familiar with macOS, but it seems that any such crashes should be recorded by the OS itself and show up in `~/Library/Logs/DiagnosticReports` - can you see if there's anything there? The crash dumps are supposed to have PIDs in the name, which should match the PID used in the filename of the pydevd log.

**Comment by GlenDC** [comment]
<https://gist.github.com/GlenDC/9469f01b4aa6eafa5e075afcfff2cba6>

That's an example. I see `EXC_BAD_INSTRUCTION`. Where it seems to fail to malloc something... But do not not really understand why it happens yet.

**Comment by GlenDC** [comment]
Wiped my entire pyenv and virtualenv code.
Also did a scan of all intel software and removed all things I found related to legacy installations of Python.

Still same thing... still crashes at start up and still not any closer to knowing why.

**Comment by GlenDC** [comment]
Tried upgrading Python to 3.11, and upgrade all dependencies of my project...
Yet still get the asme issue :rip:

**Comment by GlenDC** [comment]
You can choose to close the issue if you want. I can once again debug, but don't ask me how, as I'm not sure. Today if just works all of a sudden just again...

Things that have changed recently (as I didn't try it in some weeks):

- i use vscode developer preview
- we use python 3.11 now + all our deps have upgraded

So yeah, no clue what changed, but it works again.
