### ISSUE TITLE
issue with python 3.11.1 in visual studio code

### ISSUE THREAD

**Issue by ngangomsamananda** [microsoft/debugpy#1300]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.7
- OS and version: windows 10 enterprise 19044
- Python version (& distribution if applicable, e.g. Anaconda): 3.11.1
- Using VS Code : 

## Actual behavior
We uses Python in our application. The current version of python we are using is 3.9.6 and I want to upgrade to the newer version 3.11.1. But there is an issue I am facing with 3.11.1 version. We launch Visual studio code from our application by running python scripts. But with version 3.11.1 the visual studio code was not getting launch. The below is the traceback of the error. 

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\server\api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\server\api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\server\api.py", line 282, in listen
    _settrace(
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\server\api.py", line 45, in _settrace
    return pydevd.settrace(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2821, in settrace
    _locked_settrace(
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2881, in _locked_settrace
    py_db = PyDB()
            ^^^^^^
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 535, in __init__
    self._files_filtering = FilesFiltering()
                            ^^^^^^^^^^^^^^^^
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_filtering.py", line 117, in __init__
    library_roots = self._get_default_library_roots()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\singng\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_filtering.py", line 159, in _get_default_library_roots
    roots.append(os.path.dirname(os.__file__))
                                 ^^^^^^^^^^^
AttributeError: module 'os' has no attribute '__file__'
```
Per traceback there is no `__file__`  attribute in os module. But when I check the `__file__` attribute seems to be present. Is there any file that might be shadowing a stdlib module? How can I fix this issue? 

Note: 
1. The error is on the vscode extensions file so, I cannot make any changes on the files. 
 2. With python version 3.10.11 this issue is not present. The issue is with python 3.11.x.

## Expected  behavior

There should not have any error just like python 3.9.6 and python 3.10.11.

**Comment by gramster** [comment]
@fabioz, this seems to be happening in pydevd, any thoughts?

**Comment by gramster** [comment]
That code hasn't changed in the debugger in several years, and any native Python module (including os) should have that attribute. There's something odd going on here. You might be able to get more info to help here by editing that `pydevd_filtering.py` file and printing out what `os` is just before that line.

**Comment by judej** [comment]
@ngangomsamananda, this does not seem right. Are you able to reproduce this on a new project? It seems like shadowing could be the culprit.  


If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
