### ISSUE TITLE
Debugpy stops after a few seconds 

### ISSUE THREAD

**Issue by Lukas-J** [microsoft/debugpy#1322]
## Environment data

- debugpy version: 1.6.7
- OS and version: Official latest Python Docker Image on Fedora 38 host
- Python version: 3.11.4
- Using VS Code or Visual Studio: Yes, VS Code 1.79.2

## Actual behavior

Running Python Remote Attach starts Debugpy and therefore the flask server, but it gets shut down after a few seconds.

```
2023-06-22 16:59:16  * Serving Flask app 'server'
2023-06-22 16:59:16  * Debug mode: on
2023-06-22 16:59:16 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
2023-06-22 16:59:16  * Running on all addresses (0.0.0.0)
2023-06-22 16:59:16  * Running on http://127.0.0.1:5000
2023-06-22 16:59:16  * Running on http://172.19.0.3:5000
2023-06-22 16:59:16 Press CTRL+C to quit
2023-06-22 16:59:16  * Restarting with stat
2023-06-22 16:59:16 0.00s - Debugger warning: It seems that frozen modules are being used, which may
2023-06-22 16:59:16 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
2023-06-22 16:59:16 0.00s - to python to disable frozen modules.
2023-06-22 16:59:16 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
2023-06-22 16:59:17 0.00s - Debugger warning: It seems that frozen modules are being used, which may
2023-06-22 16:59:17 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
2023-06-22 16:59:17 0.00s - to python to disable frozen modules.
2023-06-22 16:59:17 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
2023-06-22 16:59:17 [2023-06-22 14:59:17,200] DEBUG in scheduler: Started scheduling thread (scheduler-1687445956)
2023-06-22 16:59:18 Traceback (most recent call last):
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3489, in <module>
2023-06-22 16:59:18     main()
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3482, in main
2023-06-22 16:59:18     globals = debugger.run(setup['file'], None, None, is_module)
2023-06-22 16:59:18               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2510, in run
2023-06-22 16:59:18     return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
2023-06-22 16:59:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2528, in _exec
2023-06-22 16:59:18     globals = pydevd_runpy._run_module_as_main(module_name, alter_argv=False)
2023-06-22 16:59:18               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
2023-06-22 16:59:18     return _run_code(code, main_globals, None,
2023-06-22 16:59:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
2023-06-22 16:59:18     exec(code, run_globals)
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/__main__.py", line 39, in <module>
2023-06-22 16:59:18     cli.main()
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/server/cli.py", line 430, in main
2023-06-22 16:59:18     run()
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/server/cli.py", line 268, in run_file
2023-06-22 16:59:18     start_debugging(target)
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/server/cli.py", line 256, in start_debugging
2023-06-22 16:59:18     debugpy.listen(options.address)
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/public_api.py", line 31, in wrapper
2023-06-22 16:59:18     return wrapped(*args, **kwargs)
2023-06-22 16:59:18            ^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/server/api.py", line 143, in debug
2023-06-22 16:59:18     log.reraise_exception("{0}() failed:", func.__name__, level="info")
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/server/api.py", line 141, in debug
2023-06-22 16:59:18     return func(address, settrace_kwargs, **kwargs)
2023-06-22 16:59:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-22 16:59:18   File "/usr/local/lib/python3.11/site-packages/debugpy/server/api.py", line 262, in listen
2023-06-22 16:59:18     raise RuntimeError(str(endpoints["error"]))
2023-06-22 16:59:18 RuntimeError: Can't listen for client connections: [Errno 98] Address already in use
2023-06-22 16:59:21 0.00s - Debugger warning: It seems that frozen modules are being used, which may
2023-06-22 16:59:21 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
2023-06-22 16:59:21 0.00s - to python to disable frozen modules.
2023-06-22 16:59:21 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

## Expected  behavior

Debugpy keeps running the Flask server.

## Steps to reproduce:
I've got the following configuration:

- launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/app"
                }
            ],
            "preLaunchTask": "sleep",

            "serverReadyAction": {
                "action": "openExternally",
                // "pattern": "listening on port ([0-9]+)",
                "uriFormat": "http://localhost:5000"
                // "webRoot": "${workspaceFolder}"
            }
        }
    ]
}

```
- tasks.json:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run docker-compose down",
      "type": "docker-compose",
      "dockerCompose": {
        "down": {},
        "files": [
          "${workspaceFolder}/docker-compose.dev.yml"
        ]
      }
    },
    {
      "label": "Run docker-compose up",
      "type": "docker-compose",
      "dockerCompose": {
        "up": {
          "detached": true,
          "build": true,
        },
        "files": [
          "${workspaceFolder}/docker-compose.dev.yml"
        ]
      },
      "dependsOn": "Run docker-compose down"
    },
    {
      "label": "sleep",
      "type": "shell",
      "command": "sleep 1",
      "dependsOn": "Run docker-compose up",
    }
  ]
}
```
- docker-compose.dev.yml:
```
version: '3.8'

services:
  web:
    build:
      context: .
      target: debug
    depends_on:
      - db
    environment:
      FLASK_DEBUG: "True" # For debugging only
    ports:
      - "5000:5000" # our app
      - "5678:5678" # debugpy
    restart: always
    volumes:
      - .:/app # volume for flask hot reloading
    # entrypoint:
    #   python ./server.py
    entrypoint:
      - python
      - -m
      - debugpy
      - --wait-for-client
      - --listen
      - 0.0.0.0:5678
      - server.py

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    expose:
      - "5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_config:/etc/postgresql

volumes:
  postgres_data:
  postgres_config:
```
- Dockerfile:
```
# syntax=docker/dockerfile:1

# see https://docs.docker.com/language/python/build-images/
# see https://dev.to/pacheco/dockerize-a-flask-app-and-debug-with-vscode-34i1

FROM python:3 as base

# Set location of our app
WORKDIR /app

# upgrade pip
RUN pip install --upgrade pip

# Install dependencies
COPY modules/fszoo/fszoo_submodule modules/fszoo/fszoo_submodule
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Upgrade software to latest
RUN apt-get update
RUN apt-get upgrade -y
# Set locale
RUN apt-get install -y locales
RUN sed -i '/de_DE.UTF-8/s/^# //g' /etc/locale.gen
RUN locale-gen

# Install latex dependencies
RUN apt-get install -y texlive texlive-xetex latexmk lmodern fonts-cmu texlive-science texlive-luatex texlive-lang-german texlive-bibtex-extra

# ------------------------------------

FROM base as debug
# Settings for debugging

# Expose port 5000
EXPOSE 5000

# Install debugpy for debugging and listen on port 5678
RUN pip install debugpy
EXPOSE 5678
# Force the stdout and stderr streams to be unbuffered. This option has no effect on the stdin stream.
ENV PYTHONUNBUFFERED=1

# If this is set to a non-empty string, Python won’t try to write .pyc files on the import of source modules.
ENV PYTHONDONTWRITEBYTECODE=1
```
- server.py
```
[...]
if __name__ == "__main__":
    app.run(use_reloader=True, host="0.0.0.0", port=5000)
```

**Comment by gramster** [comment]
You should be using listen on VS Code side and connect on Docker side.

**Comment by Lukas-J** [comment]
Hi @gramster,
thank you for your reply. Could you please explain further what you think I should do? 
Till now, I thought that the debugpy on Docker should listen and VScode connects to it by defining "request: attach" and "port" in launch.json.

**Comment by gramster** [comment]
My reason for suggesting that was that it looks from the logs that you are starting more than one instance, but they can't both listen on the same port. At least that's what I was inferring from the duplicated log messages:

```
2023-06-22 16:59:16 0.00s - Debugger warning: It seems that frozen modules are being used, which may
2023-06-22 16:59:16 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
2023-06-22 16:59:16 0.00s - to python to disable frozen modules.
2023-06-22 16:59:16 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
2023-06-22 16:59:17 0.00s - Debugger warning: It seems that frozen modules are being used, which may
2023-06-22 16:59:17 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
2023-06-22 16:59:17 0.00s - to python to disable frozen modules.
```

 Flipping the connection around could help with that. But maybe there is something else going on that is the underlying cause that needs to be addressed.

**Comment by judej** [comment]
@lukas-j, please reopen if Graham's suggestions don't work. Thanks.
