### ISSUE TITLE
debugpy.listen(("0.0.0.0", 5678)) - throws a time out error

### ISSUE THREAD

**Issue by zaalgol** [microsoft/debugpy#1330]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.5.1
- OS and version: Linux Debian 5.10.179-1
- Python version: host: 3.92, container: 3.6.8. pip
- Using VS Code or Visual Studio: VS code

## Actual behavior

`debugpy.listen(("0.0.0.0", 5678)) `throws an error:
```
getopt_long() error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 218, in listen
    sock, _ = endpoints_listener.accept()
  File "/usr/local/lib/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "svc/api/app.py", line 20, in <module>
    debugpy.listen(("0.0.0.0", 5678))
  File "/usr/local/lib/python3.6/site-packages/debugpy/__init__.py", line 113, in listen
    return api.listen(address)
  File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 232, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
```

## Expected  behavior

Should work without errors

## Steps to reproduce:

I run a python flask app (with Nginx, uWSGI, and Supervisor) in a docker container. 
The docker stack is deployed by docker swarm with docker-compose.

In the docker-compose.yml file I mapped the 5678 port between host and the docker service.
the command `docker service ls `shows me the mapping `*:5678->5678/tcp`.

But running the app (even without debugging) throws an error.

The code:
```
import debugpy
# starting the flask app
debugpy.listen(("0.0.0.0", 5678)) # Throws an error
```

**Comment by zaalgol** [comment]
My debugpy.to_log():


debugpy.server-1216.log:

```
I+00000.004: Linux-5.10.0-23-cloud-amd64-x86_64-with-debian-9.7 x86_64
             CPython 3.6.8 (64-bit)
             debugpy 1.5.1

I+00000.007: Initial environment:
             
             System paths:
                 sys.prefix: /usr/local
                 sys.base_prefix: /usr/local
                 sys.real_prefix: <missing>
                 site.getsitepackages(): /usr/local/lib/python3.6/site-packages
                 site.getusersitepackages(): /root/.local/lib/python3.6/site-packages
                 sys.path (site-packages): /usr/local/lib/python3.6/site-packages
                 sysconfig.get_path('stdlib'): /usr/local/lib/python3.6
                 sysconfig.get_path('platstdlib'): /usr/local/lib/python3.6
                 sysconfig.get_path('purelib'): /usr/local/lib/python3.6/site-packages
                 sysconfig.get_path('platlib'): /usr/local/lib/python3.6/site-packages
                 sysconfig.get_path('include'): /usr/local/include/python3.6m
                 sysconfig.get_path('scripts'): /usr/local/bin
                 sysconfig.get_path('data'): /usr/local
                 os.__file__: /usr/local/lib/python3.6/os.py
                 threading.__file__: /usr/local/lib/python3.6/threading.py

D+00000.007: listen(('127.0.0.1', 5678), **{})

I+00000.007: Initial debug configuration: {
                 "qt": "none",
                 "subProcess": true,
                 "python": "/usr/local/bin/uwsgi"
             }

I+00000.008: Waiting for adapter endpoints on 127.0.0.1:35727...

I+00000.008: debugpy.listen() spawning adapter: [
                 "/usr/local/bin/uwsgi",
                 "/usr/local/lib/python3.6/site-packages/debugpy/adapter",
                 "--for-server",
                 "35727",
                 "--host",
                 "127.0.0.1",
                 "--port",
                 "5678",
                 "--server-access-token",
                 "744e3668cd67e730b4738c718dedc41bdfba535503442accd38f134cdf02faad",
                 "--log-dir",
                 "debugpylogs"
             ]

```


debugpy.server-1332.log:

```
I+00000.002: Linux-5.10.0-23-cloud-amd64-x86_64-with-debian-9.7 x86_64
             CPython 3.6.8 (64-bit)
             debugpy 1.5.1

I+00000.006: Initial environment:
             
             System paths:
                 sys.prefix: /usr/local
                 sys.base_prefix: /usr/local
                 sys.real_prefix: <missing>
                 site.getsitepackages(): /usr/local/lib/python3.6/site-packages
                 site.getusersitepackages(): /root/.local/lib/python3.6/site-packages
                 sys.path (site-packages): /usr/local/lib/python3.6/site-packages
                 sysconfig.get_path('stdlib'): /usr/local/lib/python3.6
                 sysconfig.get_path('platstdlib'): /usr/local/lib/python3.6
                 sysconfig.get_path('purelib'): /usr/local/lib/python3.6/site-packages
                 sysconfig.get_path('platlib'): /usr/local/lib/python3.6/site-packages
                 sysconfig.get_path('include'): /usr/local/include/python3.6m
                 sysconfig.get_path('scripts'): /usr/local/bin
                 sysconfig.get_path('data'): /usr/local
                 os.__file__: /usr/local/lib/python3.6/os.py
                 threading.__file__: /usr/local/lib/python3.6/threading.py

D+00000.006: listen(('127.0.0.1', 5678), **{})

I+00000.006: Initial debug configuration: {
                 "qt": "none",
                 "subProcess": true,
                 "python": "/usr/local/bin/uwsgi"
             }

I+00000.007: Waiting for adapter endpoints on 127.0.0.1:41925...

I+00000.007: debugpy.listen() spawning adapter: [
                 "/usr/local/bin/uwsgi",
                 "/usr/local/lib/python3.6/site-packages/debugpy/adapter",
                 "--for-server",
                 "41925",
                 "--host",
                 "127.0.0.1",
                 "--port",
                 "5678",
                 "--server-access-token",
                 "4210596272d70a989aea7bed719bf07596df3b5f6eb34a47ebc924caa035e334",
                 "--log-dir",
                 "debugpylogs"
             ]

I+00010.024: Timed out waiting for adapter to connect:
             
             Traceback (most recent call last):
               File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 218, in listen
                 sock, _ = endpoints_listener.accept()
               File "/usr/local/lib/python3.6/socket.py", line 205, in accept
                 fd, addr = self._accept()
             socket.timeout: timed out
             
             Stack where logged:
               File "svc/api/app.py", line 20, in <module>
                 debugpy.listen(5678)
               File "/usr/local/lib/python3.6/site-packages/debugpy/__init__.py", line 113, in listen
                 return api.listen(address)
               File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 141, in debug
                 return func(address, settrace_kwargs, **kwargs)
               File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 230, in listen
                 "Timed out waiting for adapter to connect:", level="info"
               File "/usr/local/lib/python3.6/site-packages/debugpy/common/log.py", line 218, in swallow_exception
                 _exception(format_string, *args, **kwargs)
             

I+00010.024: listen() failed:
             
             Traceback (most recent call last):
               File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 218, in listen
                 sock, _ = endpoints_listener.accept()
               File "/usr/local/lib/python3.6/socket.py", line 205, in accept
                 fd, addr = self._accept()
             socket.timeout: timed out
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
               File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 141, in debug
                 return func(address, settrace_kwargs, **kwargs)
               File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 232, in listen
                 raise RuntimeError("timed out waiting for adapter to connect")
             RuntimeError: timed out waiting for adapter to connect
             
             Stack where logged:
               File "svc/api/app.py", line 20, in <module>
                 debugpy.listen(5678)
               File "/usr/local/lib/python3.6/site-packages/debugpy/__init__.py", line 113, in listen
                 return api.listen(address)
               File "/usr/local/lib/python3.6/site-packages/debugpy/server/api.py", line 143, in debug
                 log.reraise_exception("{0}() failed:", func.__name__, level="info")
               File "/usr/local/lib/python3.6/site-packages/debugpy/common/log.py", line 226, in reraise_exception
                 _exception(format_string, *args, **kwargs)
             
```

**Comment by antoine79** [comment]
I had a similar problem while it works just fine with ptvsd. Of course I try to attach/connect to that process before it times out, but I get rejected as if the port had never been openned.

**Comment by int19h** [comment]
The problem is that your code is not running under a regular Python interpreter, but rather under `uwsgi`, which then becomes `sys.executable`. Debugpy needs a Python interpreter to run its helper processes, and it assumes that `sys.executable` is one by default, but in hosted scenarios like this it's not a correct assumption.

You can tell it which interpreter to use like so:
```py
debugpy.configure(python="/usr/bin/python3")
```
(it doesn't need to match the version of Python that you're using to run your app)
