### ISSUE TITLE
When debugging a pytest unittest in VSCode, the python debugger detaches after ~60s, and I can't find an overriding timeout setting

### ISSUE THREAD

**Issue by haughki** [microsoft/debugpy#1347]
Type: <b>Bug</b>

# Behaviour
## Expected
When debugging a pytest unittest using the inline right-click debug from a specific test, I can debug for as long as I want; i.e., the debugger stays connected and breaks on breakpoints, etc., without timing out, OR the extension allows me to set a timeout for as long as I want.

## Actual
The debugger times out and disconnects after 60 seconds, and I can't seem to find any setting to increase the timeout.

## Steps to reproduce:

1. Set a break point in a pytest unittest in VSCode. Here is the test I am using, with a breakpoint on the 'print(...' line:
```
def test_set_breakpoint_and_watch_test_timeout():
    """dummy test"""
    print("This test does nothing.")
```
2. Right-click on the green "Play" button next to the name of the unittest in the left gutter of the VSCode editor.
3. Select "Debug Test".
4. The debugger should break on the breakpoint
5. Wait for ~70 secs.

### Expected
The debugger stays attached and I can keep debugging -- viewing variable data, stepping through code, etc.

### Actual
The debugger detatches after ~60s and reports the following error (full DEBUG CONSOLE output below):

```
...
...
            self.process_internal_commands()
>           time.sleep(0.01)
E           Failed: Timeout >60.0s

../../.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py:2106: Failed
=========================== short test summary info ============================
FAILED tests/operations/test_sequence_to_helm.py::test_set_breakpoint_and_watch_test_timeout
========================= 1 failed in 61.99s (0:01:01) =========================
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
OUTPUT - Python
2023-08-07 11:59:40.858 [info] Running PYTEST execution for the following test ids: tests/operations/test_sequence_to_helm.py::test_set_breakpoint_and_watch_test_timeout
2023-08-07 11:59:40.858 [info] Server listening on port 37781
2023-08-07 11:59:40.858 [info] Running DEBUG pytest with arguments: --rootdir /home/hawk/projects/cdd_peptide_reg --capture no

2023-08-07 11:59:40.860 [info] Using launch configuration in launch.json file.
2023-08-07 11:59:41.352 [info] DAP Server launched with command: /home/hawk/projects/cdd_peptide_reg/conenv/bin/python /home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter
2023-08-07 12:00:44.798 [info] Test server connected to a client.
2023-08-07 12:00:45.596 [info] Client disconnected
```

```
DEBUG CONSOLE OUTPUT

CLIENT: Server listening on port 37781...
Received JSON data: ['tests/operations/test_sequence_to_helm.py::test_set_breakpoint_and_watch_test_timeout']
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/hawk/projects/cdd_peptide_reg, configfile: pyproject.toml
plugins: forked-1.3.0, asyncio-0.15.1, cov-3.0.0, datadir-1.4.1, pytest_check-1.0.4, xdist-2.5.0, timeout-1.4.2, anyio-3.5.0
timeout: 60.0s
timeout method: signal
timeout func_only: False
collected 1 item

tests/operations/test_sequence_to_helm.py

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (140534510081600) ~~~~~~~~~~~~~~~~~~~~~
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 1118, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49, in run
    self._on_run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_timeout.py", line 43, in _on_run
    self._event.wait(wait_time)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (140534518474304) ~~~~~~~~~~~~~~~~~~~~~
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49, in run
    self._on_run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 261, in _on_run
    self._wait_event.wait(0.3)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (140534526867008) ~~~~~~~~~~~~~~~~~~~~~
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49, in run
    self._on_run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 215, in _on_run
    self._py_db_command_thread_event.wait(0.3)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (140534536046144) ~~~~~~~~~~~~~~~~~~~~~
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49, in run
    self._on_run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 222, in _on_run
    line = self._read_line()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 204, in _read_line
    r = self.sock.recv(1024)

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (140534544438848) ~~~~~~~~~~~~~~~~~~~~~
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49, in run
    self._on_run()
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 368, in _on_run
    cmd = self._cmd_queue.get(True, 0.1)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
<class 'Failed'> raised from within the callback set in sys.settrace.
Debugging will be disabled for this thread (<_MainThread(MainThread, started 140534571606976)>).
Traceback (most recent call last):
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 988, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "/home/hawk/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend
    time.sleep(0.01)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/site-packages/pytest_timeout.py", line 200, in handler
    timeout_sigalrm(item, params.timeout)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/site-packages/pytest_timeout.py", line 375, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % timeout)
  File "/home/hawk/projects/cdd_peptide_reg/conenv/lib/python3.9/site-packages/_pytest/outcomes.py", line 196, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Timeout >60.0s
Fpytest session has finished, exit status:  ExitCode.TESTS_FAILED in discovery?  False


=================================== FAILURES ===================================
__________________ test_set_breakpoint_and_watch_test_timeout __________________

    def test_set_breakpoint_and_watch_test_timeout():
        """dummy test"""
>       print("This test does nothing.")
tests/operations/test_sequence_to_helm.py:530:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/operations/test_sequence_to_helm.py:530: in test_set_breakpoint_and_watch_test_timeout
    print("This test does nothing.")
../../.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py:988: in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
../../.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py:165: in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
../../.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py:2070: in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pydevd.PyDB object at 0x7fd0bf9ba2e0>
thread = <_MainThread(MainThread, started 140534571606976)>
frame = <frame at 0x7fd0a1d97040, file '/home/hawk/projects/cdd_peptide_reg/tests/operations/test_sequence_to_helm.py', line 530, code test_set_breakpoint_and_watch_test_timeout>
event = 'line', arg = None, suspend_type = 'trace', from_this_thread = []
frames_tracker = <_pydevd_bundle.pydevd_suspended_frames._FramesTracker object at 0x7fd0a1d94be0>
    def _do_wait_suspend(self, thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker):
        info = thread.additional_info
        info.step_in_initial_location = None
        keep_suspended = False
    
        with self._main_lock:  # Use lock to check if suspended state changed
            activate_gui = info.pydev_state == STATE_SUSPEND and not self.pydb_disposed
        in_main_thread = is_current_thread_main_thread()
        if activate_gui and in_main_thread:
            # before every stop check if matplotlib modules were imported inside script code
            # or some GUI event loop needs to be activated
            self._activate_gui_if_needed()
    
        while True:
            with self._main_lock:  # Use lock to check if suspended state changed
                if info.pydev_state != STATE_SUSPEND or (self.pydb_disposed and not self.terminate_requested):
                    # Note: we can't exit here if terminate was requested while a breakpoint was hit.
                    break
            if in_main_thread and self.gui_in_use:
                # call input hooks if only GUI is in use
                self._call_input_hook()
    
            self.process_internal_commands()
>           time.sleep(0.01)
E           Failed: Timeout >60.0s

../../.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py:2106: Failed
=========================== short test summary info ============================
FAILED tests/operations/test_sequence_to_helm.py::test_set_breakpoint_and_watch_test_timeout
========================= 1 failed in 61.58s (0:01:01) =========================
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• pylintArgs: "<placeholder>"

testing
• pytestEnabled: true

terminal
• activateEnvironment: false

```

</p>
</details>

Extension version: 2023.14.0
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (2.46GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu/home/hawk/projects/cdd_peptide_reg/registration.code-workspace --remote=wsl+Ubuntu --crash-reporter-id ea39c7bc-9acf-4ab0-a8de-b9cec0c6fcb0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (4 x 1896)|
|Memory (System)|3.84GB (2.96GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by youssefelmasry** [comment]
hello @haughki 

You can set the timeout of pytest from two places, you can either set in `pyproject.toml` file or `settings.json` where it can be created under .vscode directory (or at the same directory where launch.json is):
1. if you have `pyproject.tom` file it can be like this:
```
[tool.pytest.ini_options]
....
timeout = 0
```
2. in `settings.json`:
```
{
    ...
    "python.testing.pytestArgs: ["--timeout=0", ]
}
```
**PS: you can set the timeout value whatever you want, 0 means it will never detaches**

**Comment by haughki** [comment]
@youssefelmasry Hi! So sorry -- somehow I missed your comment until just now.

Yes! That worked and fixes my problem %100. Thank you so much for taking the time to help me.
