### ISSUE TITLE
test_gevent crashing on Python 3.11

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1356]
```
E+02.016: /handling #11 event "exited" from Adapter[1]/
          Handler 'Session._process_event' (file 'C:\\git\\debugpy\\tests\\debug\\session.py', line 484)
          couldn't handle #11 event "exited" from Adapter[1]:

          Traceback (most recent call last):
            File "C:\git\debugpy\.tox\py311\Lib\site-packages\debugpy\common\messaging.py", line 582, in _handle
              result = handler(self)
                       ^^^^^^^^^^^^^
            File "C:\git\debugpy\tests\debug\session.py", line 490, in _process_event
              assert self.exit_code == self.expected_exit_code
          AssertionError: assert 3221225477 == 0
           +  where 3221225477 = <tests.debug.session.Session object at 0x000002439BCDFE10>.exit_code
           +  and   0 = <tests.debug.session.Session object at 0x000002439BCDFE10>.expected_exit_code
```
3221225477 is 0xC0000005, which corresponds to STATUS_ACCESS_VIOLATION.

**Comment by int19h** [comment]
This is because we're running with an old version of greenlet due to https://github.com/microsoft/debugpy/issues/1126. The latter has been resolved upstream a while ago, and unpinning greenlet resolves the issue.
