### ISSUE TITLE
Step into, step out, step over, continue all works the same

### ISSUE THREAD

**Issue by XJTLUmedia** [microsoft/debugpy#1417]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.6 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Windows NT_x64 10.0
- Python version (& distribution if applicable, e.g. Anaconda): 3.11.5
- Using VS Code or Visual Studio: VSCode 1.85.0-insider

## Actual behavior

```python

    tickers=['SPY','QQQ']
    start_date=datetime.today()-timedelta(days=400)
    end_date=datetime.today()
    stock_data_close = pd.DataFrame(yf.download(tickers, start=start_date, end=end_date)['Adj Close'])
```

If I set a breakpoint in stock_data_close, when I closed the internet and run python file, it would get an error.

```
Traceback (most recent call last):
  File "C:\App\python\Lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "C:\App\python\Lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\http\client.py", line 466, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\App\python\Lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\App\python\Lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\urllib3\response.py", line 566, in read
    with self._error_catcher():
  File "C:\App\python\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\App\python\Lib\site-packages\urllib3\response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\App\python\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\ASUS\.vscode-insiders\extensions\ms-python.python-2023.21.13071013\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\ASUS\.vscode-insiders\extensions\ms-python.python-2023.21.13071013\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\ASUS\.vscode-insiders\extensions\ms-python.python-2023.21.13071013\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\ASUS\.vscode-insiders\extensions\ms-python.python-2023.21.13071013\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ASUS\.vscode-insiders\extensions\ms-python.python-2023.21.13071013\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\ASUS\.vscode-insiders\extensions\ms-python.python-2023.21.13071013\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Study\Finance\randomforest.py", line 23, in <module>
    stock_data_close,stock_data_open,stock_data_high,stock_data_low,stock_data_volume,stock_market_cap=getcsv.getcsv()
                                                                                                       ^^^^^^^^^^^^^^^
  File "c:\Study\Finance\getcsv.py", line 21, in getcsv
    stock_market_cap=web.get_quote_yahoo(tickers)['marketCap']
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\pandas_datareader\data.py", line 96, in get_quote_yahoo
    return YahooQuotesReader(*args, **kwargs).read()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\pandas_datareader\yahoo\quotes.py", line 53, in read
    data[symbol] = self._read_one_data(self.url, self.params(symbol)).loc[
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\pandas_datareader\base.py", line 108, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\pandas_datareader\base.py", line 119, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\pandas_datareader\base.py", line 155, in _get_response
    response = self.session.get(
               ^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\requests\sessions.py", line 747, in send
    r.content
  File "C:\App\python\Lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\App\python\Lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Read timed out
```

No matter which button I clicked (step into, step out, step over, continue), all of them exit debug mode and finish the running process with an error in terminal window

## Expected  behavior

If I clicked step in, it should be able to jump file to file from get_csv.py web.get_quote_yahoo(tickers)['marketCap'] to models.py sentence of ConnectionError(e) just like error output

## Steps to reproduce:
1. XXX

**Comment by int19h** [comment]
You have an unhandled exception in your code. Exceptions aren't resumable in Python - you can't just "step over" it, the next line after the exception is always going to be the actual handler for said exception, but you don't have any handlers here, so there's nothing to step to.
