### ISSUE TITLE
Undocumented gdb Version (> 11.1) Requirements for Python Attach Mode 

### ISSUE THREAD

**Issue by realaslam786** [microsoft/debugpy#1480]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Minimum gdb version requirements need to be clearly specified.

## Steps to reproduce:

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.18
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Unknown
-   Value of the `python.languageServer` setting: Default

<details>

<summary>There are undocumented (implicit) requirements on having <code>gdb</code> version &gt; **11.1** available for <code>Python Attach</code> debug configuration to work.

1) The requirement to have a <code>gdb</code> installation available in the `Path` is not documented as the pre-requisites for the extension. A <code>gdb</code> in <code>Path</code> is needed for the Python Attach mode debug configurations to work. 

2) The minimum <code>gdb</code> requirement is not specified. The extension fails to attach to an existing process with <code>gdb</code> version **11.1**. However, it has been successfully tested with <code>gdb</code> version **12.1**. With <code>gdb</code> version **11.1**. The following is part of the error logs shown in the <code>Debug Console</code> for `gdb` version **11.1**.

<code>
Attach to PID failed.

--- Starting attach to pid: xx---
[New LWP xx]
[New LWP xx]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f4c08f5170c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
The target architecture is set to "auto" (currently "i386:x86-64").
Couldn't write extended state status: Bad address.
No symbol "DoAttach" in current context.
[Inferior 1 (process 136643) detached]
E+00003.400: Code injection into PID=136643 failed

Traceback (most recent call last):
               File "/.../ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 391, in attach_to_pid
                 add_code_to_python_process.run_python_code(
               File "/.../ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 471, in run_python_code_linux
                 subprocess.check_call(' '.join(cmd), shell=True, env=env)
               File "/...//python3.9/subprocess.py", line 373, in check_call
                 raise CalledProcessError(retcode, cmd)
             subprocess.CalledProcessError: Command 'gdb --nw --nh --nx --pid 136643 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture auto' --eval-command='call (void*)dlopen("/.../ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='sharedlibrary attach_linux_amd64' --eval-command='call (int)DoAttach(0, "import codecs;import json;import sys;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0] if s is not None else None;script_dir = decode ...
</code>  
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.16.0
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.14.21-150400.22-default
Remote OS version: Linux x64 5.14.21-150400.22-default

**Comment by xsank** [comment]
gdb 12.1 with the same problem...
```shell
[New LWP 483611]
[New LWP 483615]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55b7d5e37ab0) at ./nptl/futex-internal.c:57
57	./nptl/futex-internal.c: No such file or directory.
The target architecture is set to "auto" (currently "i386:x86-64").
Couldn't write extended state status: Bad address.
No symbol "DoAttach" in current context.
[Inferior 1 (process 473713) detached]
E+00004.804: Code injection into PID=473713 failed:
             
             Traceback (most recent call last):
               File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 461, in attach_to_pid
                 add_code_to_python_process.run_python_code(
               File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 480, in run_python_code_linux
                 subprocess.check_call(" ".join(cmd), shell=True, env=env)
               File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
                 raise CalledProcessError(retcode, cmd)
             subprocess.CalledProcessError: Command 'gdb --nw --nh --nx --pid 473713 --batch --eval-command='set scheduler-locking off' --eval-command='set architecture auto' --eval-command='call (void*)dlopen("/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)' --eval-command='sharedlibrary attach_linux_amd64' --eval-command='call (int)DoAttach(0, "import codecs;import json;import sys;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0] if s is not None else None;script_dir = decode([47, 114, 111, 111, 116, 47, 46, 118, 115, 99, 111, 100, 101, 45, 115, 101, 114, 118, 101, 114, 47, 101, 120, 116, 101, 110, 115, 105, 111, 110, 115, 47, 109, 115, 45, 112, 121, 116, 104, 111, 110, 46, 100, 101, 98, 117, 103, 112, 121, 45, 50, 48, 50, 53, 46, 56, 46, 48, 45, 108, 105, 110, 117, 120, 45, 120, 54, 52, 47, 98, 117, 110, 100, 108, 101, 100, 47, 108, 105, 98, 115, 47, 100, 101, 98, 117, 103, 112, 121, 47, 97, 100, 97, 112, 116, 101, 114, 47, 46, 46, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 46, 46, 47, 100, 101, 98, 117, 103, 112, 121, 47, 115, 101, 114, 118, 101, 114]);setup = json.loads(decode([123, 34, 109, 111, 100, 101, 34, 58, 32, 34, 99, 111, 110, 110, 101, 99, 116, 34, 44, 32, 34, 97, 100, 100, 114, 101, 115, 115, 34, 58, 32, 91, 34, 49, 50, 55, 46, 48, 46, 48, 46, 49, 34, 44, 32, 53, 53, 50, 56, 55, 93, 44, 32, 34, 119, 97, 105, 116, 95, 102, 111, 114, 95, 99, 108, 105, 101, 110, 116, 34, 58, 32, 102, 97, 108, 115, 101, 44, 32, 34, 108, 111, 103, 95, 116, 111, 34, 58, 32, 110, 117, 108, 108, 44, 32, 34, 97, 100, 97, 112, 116, 101, 114, 95, 97, 99, 99, 101, 115, 115, 95, 116, 111, 107, 101, 110, 34, 58, 32, 34, 101, 102, 54, 102, 56, 54, 57, 102, 48, 98, 56, 55, 100, 49, 99, 51, 53, 101, 98, 52, 55, 50, 53, 55, 56, 51, 52, 53, 100, 54, 54, 101, 102, 55, 98, 52, 50, 98, 100, 100, 52, 101, 55, 48, 49, 50, 101, 97, 102, 101, 48, 54, 99, 51, 49, 101, 98, 101, 99, 56, 49, 53, 56, 97, 34, 125]));sys.path.insert(0, script_dir);import attach_pid_injected;del sys.path[0];attach_pid_injected.attach(setup);", 0)'' returned non-zero exit status 1.
             
             Stack where logged:
               File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
                 exec(code, run_globals)
               File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/__main__.py", line 71, in <module>
                 cli.main()
               File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 501, in main
                 run()
               File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 468, in attach_to_pid
                 log.reraise_exception("Code injection into PID={0} failed:", pid)
               File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/common/log.py", line 222, in reraise_exception
                 _exception(format_string, *args, **kwargs)
             

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 468, in attach_to_pid
    log.reraise_exception("Code injection into PID={0} failed:", pid)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/../debugpy/server/cli.py", line 461, in attach_to_pid
    add_code_to_python_process.run_python_code(
  File "/root/.vscode-server/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd_attach_to_process/add_code_to_python_process.py", line 480, in run_python_code_linux
    subprocess.check_call(" ".join(cmd), shell=True, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
```

env
```shell
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by rchiodo** [comment]
This will all be a moot point once 3.14 ships as it handles attach for us.

**Comment by xsank** [comment]
> This will all be a moot point once 3.14 ships as it handles attach for us.

What?

**Comment by rchiodo** [comment]
This PEP here:
https://peps.python.org/pep-0768/
