### ISSUE TITLE
`set_trace`-releated deadlock when running inside Ansible with explicit listen-and-debug breakpoint

### ISSUE THREAD

**Issue by domq** [microsoft/debugpy#1519]
## Environment data

- debugpy version: 1.8.1 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Mac OS X Sonoma 14.2.1 (23C71)
- Python version: Python 3.11.7 that comes with Mac OS X
- Using VS Code version 1.86.1 (likely irrelevant, as I observe the same behavior with Emacs and [dape.el](https://github.com/svaante/dape))

## Actual behavior

Upon attempting to attach the client,

- Variables → Locals keeps spinning inside VS Code
- Debugger is catatonic; every command times out (same when tried out of Emacs)
- Pressing C-c yields the following stack trace (even after waiting for several minutes):

```
^CTraceback (most recent call last):
  File "/Users/quatrava/Dev/ops/xaasible-ops/ansible-deps-cache/python-libs/lib/python/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3489, in <module>
 [ERROR]: User interrupted execution
    main()
  File "/Users/quatrava/Dev/ops/xaasible-ops/ansible-deps-cache/python-libs/lib/python/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3482, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quatrava/Dev/ops/xaasible-ops/ansible-deps-cache/python-libs/lib/python/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2476, in run
    self.wait_for_ready_to_run()
  File "/Users/quatrava/Dev/ops/xaasible-ops/ansible-deps-cache/python-libs/lib/python/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 838, in wait_for_ready_to_run
    self._py_db_command_thread_event.wait(0.1)
  File "/usr/local/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

## Expected  behavior

Debugger session should proceed as usual, even though some slow JSON-RPCs are expected (i.e. because my test case has large visible variables). Note that that is exactly what happens if instead of running Ansible, I run a hello-world Python script that features the same `debugpy` stanza to await debugger connect, i.e.

```python
import debugpy; debugpy.listen(5678); debugpy.wait_for_client(); debugpy.breakpoint()

print("hello world")
```

## Steps to reproduce:

1. Configure VS Code as per [the documentation](https://code.visualstudio.com/docs/python/debugging). My `.vscode/launch.json` is attached below
2. Install Ansible
3. Create `lookup_plugins/my_python_lookup.py` and add the following code inside: 
    ```python
    from ansible.plugins.lookup import LookupBase

    class LookupModule(LookupBase):
        def run(self, terms, variables=None, **kwargs):
            import debugpy; debugpy.listen(5678); debugpy.wait_for_client(); debugpy.breakpoint()

            return ["toto"]
    ```
4. Prepare a trivial Ansible playbook that calls `'{{ lookup("my_python_lookup") }}'` somewhere
5.  Run the Ansible playbook
<details>

## Attachments

  <summary><code>.vscode/launch.json</code></summary>

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Débogueur Python : Attachement à distance",
            "type": "debugpy",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        }
    ]
}
```

</details>

**Comment by domq** [comment]
The reason why I filed the issue here, and also the reason for the title, is that the attached patch makes the symptom go away.

[0001-hack-Make-https-github.com-microsoft-debugpy-issues-.patch](https://github.com/microsoft/debugpy/files/14237970/0001-hack-Make-https-github.com-microsoft-debugpy-issues-.patch)

**Comment by int19h** [comment]
`sys.settrace` is needed for core debugger functionality - that's how stepping and breakpoints are implemented. By disabling it, you effectively disable those features in the process in which it is omitted. IIRC for Google App Engine this is fine because you don't actually care about debugging the main process, only the subprocesses that it spawns. But is that also the case for Ansible?

That said, the problem with App Engine is that it monkey-patches much of the Python standard library to do its own thing instead, and uses `settrace` itself, which conflicts with debuggers. But I couldn't find any mention of `settrace` in Ansible repo outside of test code, so it shouldn't interfere with the debugger. The issue with `wait_for_ready_to_run` is thus different.

Now, `wait_for_ready_to_run` basically waits for the DAP "configurationDone" request to arrive from the client, indicating that the client has set all the breakpoints and done other things that should be done before user code starts running. If this is not done, it means that some breakpoints in that process may be skipped because that code happens to execute before the breakpoints are actually set by the client.  However, the bigger concern is *why* this is not happening; it would seem to indicate that Ansible either does something about the sockets that blocks reads, or something about threads that causes the thread that processes incoming messages to not run. A proper fix here requires figuring out that root cause.

Could you enable logging by doing `debugpy.log_to("/some/directory")` and see what `debugpy.pydevd*.log` says?

I also wonder what happens if you use `debugpy.connect()` instead of `debugpy.listen()` (and, conversely, "listen" rather than "connect" in your launch.json). Aside from reversing the direction of connection, it also moves responsibility for spawning the debug adapter process from the debuggee to VSCode; perhaps that would make a difference?

**Comment by domq** [comment]
So, I wish I was kidding, but turning debugging on makes the issue go away 😬 See for yourself...

![debugpy](https://github.com/microsoft/debugpy/assets/1629585/ea674341-f595-41a5-8c91-00247cd3ef98)

**Comment by domq** [comment]
Doing the connection the other way round (i.e. VS Code being the server and the debuggee script, or rather, its `debugpy/adapter` delegate, is the client) works fine — except for a little detail which may or may not provide the clue to the whole riddle: *the debugger immediately jumps past the next line after the breakpoint,* i.e. it returns to the caller frame instead of waiting at the `return` line as it should.

![debugpy-client](https://github.com/microsoft/debugpy/assets/1629585/da84f4c3-668c-4615-b61e-5c83cd157da9)



It is also worth mentioning that there is no longer a need for `debugpy.wait_for_client();` in that situation, i.e. my lookup plugin file now reads

```python
from ansible.plugins.lookup import LookupBase

class LookupModule(LookupBase):
    def run(self, terms, variables=None, **kwargs):
        import debugpy; debugpy.connect(5678); debugpy.breakpoint()

        return ["toto"]
```

**Comment by domq** [comment]
> So, I wish I was kidding, but turning debugging on makes the issue go away 😬 See for yourself...

In fact, debugpy works *really* well with Emacs now! Thanks for the workaround ☺
