### ISSUE TITLE
Running debugging shows errors, but the functionality is normal.

### ISSUE THREAD

**Issue by BEISNWKZNAN** [microsoft/debugpy#1521]
## Environment data

- debugpy version: 1.7.0
- OS and version: Archlinux with Kernel linux-zen-6.7.4
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.18 in venv and 3.11.7 outside
- Using VS Code or Visual Studio: VS Code

## Actual behavior
Running debugging shows errors, but the functionality is normal.The error messages are as follows:

```
             Traceback (most recent call last):
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'
             
             Stack where logged:
               File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/__main__.py", line 91, in <module>
                 main()
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/__main__.py", line 21, in main
                 log.describe_environment("debugpy.launcher startup environment:")
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
             

E+00000.018: Error while enumerating installed packages.
             
             Traceback (most recent call last):
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/common/log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'
             
             Stack where logged:
               File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
                 cli.main()
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 415, in main
                 api.ensure_logging()
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/api.py", line 61, in ensure_logging
                 log.describe_environment("Initial environment:")
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/common/log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/common/log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
             

E+00000.333: Error while enumerating installed packages.
             
             Traceback (most recent call last):
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/common/log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'
             
             Stack where logged:
               File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
                 cli.main()
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
                 run()
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 281, in run_file
                 log.describe_environment("Pre-launch environment:")
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/common/log.py", line 369, in describe_environment
                 info("{0}", get_environment_description(header))
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/common/log.py", line 363, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "/home/beis/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)
```
And when i install importlib-metadata in my Virtual environment,The error messages disappear.But in my usage, importlib-metadata is unnecessary.

**Comment by int19h** [comment]
It is a logging error, hence why it's not critical and doesn't affect the actual debugging experience. Still a bug, though; thank you for reporting!

**Comment by int19h** [comment]
I'm really curious as to which package is actually triggering it, because `name` is not supposed to be optional.

As a workaround, you can edit the file in which it reports the error (.../debugpy/common/log.py) and replace the offending line:
```py
report("    {0}=={1}\n", pkg.name, pkg.version)
```
with `pass`.

**Comment by hunter-xue** [comment]
the same issue on MacOS with conda. all vscode plugins are updated.

**Comment by alexzt0131** [comment]
> I'm really curious as to which package is actually triggering it, because `name` is not supposed to be optional.
> 
> As a workaround, you can edit the file in which it reports the error (.../debugpy/common/log.py) and replace the offending line:
> 
> ```python
> report("    {0}=={1}\n", pkg.name, pkg.version)
> ```
> 
> with `pass`.

it worked, thank you.

**Comment by np-udri** [comment]
I've also been experiencing this bug in the last month. I am on the latest VS Code 1.86.2 on Ubuntu 20.04.

**Comment by jcita** [comment]
I have the same issue i can working but is a horrible message

**Comment by tim-jones** [comment]
I installed the missing package importlib-metadata and this error went away. vscode 1.85.1

**Comment by Crayon-ShinChan** [comment]
> I installed the missing package importlib-metadata and this error went away. vscode 1.85.1

Thanks for the solution. It works for me. 

```bash
> code --version
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
arm64

> sw_vers
ProductName:            macOS
ProductVersion:         14.2.1
BuildVersion:           23C71
```
