### ISSUE TITLE
Allow clients to debug code from command line, like pdb or epdb 

### ISSUE THREAD

**Issue by musikele** [microsoft/debugpy#1568]
Hi there, 
in my company many don't use VSCode. For this reason our main guidelines to debug are to use `pdb` or `epdb`. (https://pypi.org/project/epdb/)
However, in an effort to have just one library that works for all use cases, I'd like to have debugpy to work from command line too.

I have tried this: 

```
python -m debugpy --connect 5678 <path of the file with debugpy.listen()> 

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 252, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 171, in process_net_command_json
    method_name = 'on_%s_request' % (request.command.lower(),)
AttributeError: 'OutputEvent' object has no attribute 'command'
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/server/cli.py", line 268, in run_file
    start_debugging(target)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/server/cli.py", line 258, in start_debugging
    debugpy.connect(options.address, access_token=options.adapter_access_token)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/server/api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/server/api.py", line 297, in connect
    _settrace(host=host, port=port, client_access_token=access_token, **settrace_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/server/api.py", line 45, in _settrace
    return pydevd.settrace(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2821, in settrace
    _locked_settrace(
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2929, in _locked_settrace
    py_db.wait_for_ready_to_run()
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 838, in wait_for_ready_to_run
    self._py_db_command_thread_event.wait(0.1)
  File "/usr/local/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
```

doesn't stop in debug.

I've also tried to use debugpy in python shell: 

```
>>> import debugpy
>>> debugpy.connect(5678)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 252, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "/root/.cache/pypoetry/virtualenvs/viralize-adserver-9TtSrW0h-py3.8/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 171, in process_net_command_json
    method_name = 'on_%s_request' % (request.command.lower(),)
AttributeError: 'OutputEvent' object has no attribute 'command'
``` 

What is supposed to be this "command"? 

Also, am I doing something that is intended to be used like this, or what? I think no, because there is no such reference on the web.

**Comment by int19h** [comment]
debugpy is purely a DAP (debug adapter protocol) server/adapter implementation; it is not a DAP client like VSCode. The terms "listen" and "connect" in its API and CLI refer solely to the direction of connection between it and the client - you can have debugpy listen for an incoming connection from the client, or you can have the client listen and debugpy connect to it.

For your scenario, you should look at alternative DAP clients; [this list](https://microsoft.github.io/debug-adapter-protocol/implementors/tools/) is a good starting point. I'm not aware of any DAP client that is similar to pdb in UX, but if you just want something that is not tied to VSCode and capable of running in text mode, I would recommend looking at [Vimspector](https://puremourning.github.io/vimspector-web/) - they specifically support debugpy. 

That aside, given that the [protocol](https://microsoft.github.io/debug-adapter-protocol/specification) is very high-level, making a custom pdb-like CLI wrapper around it should be fairly straightforward. If you go down that route, you can reuse the [implementation of the messaging layer](https://github.com/microsoft/debugpy/blob/main/src/debugpy/common/messaging.py) from debugpy, and perhaps also look at our [test client](https://github.com/microsoft/debugpy/blob/main/tests/debug/session.py) that is used to drive debugpy functional tests.

**Comment by jpic** [comment]
madbg works fine for the moment
