### ISSUE TITLE
 'PathDistribution' object has no attribute 'name'

### ISSUE THREAD

**Issue by kazeki** [microsoft/debugpy#1643]
### python version:
3.8.19

### launch.json
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
        }
    ]
}
``` 

### error message
```shell
E+00000.072: Error while enumerating installed packages.
             
             Traceback (most recent call last):
               File "/home/xhdev/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 361, in get_environment_description
                 report("    {0}=={1}\n", pkg.name, pkg.version)
             AttributeError: 'PathDistribution' object has no attribute 'name'
             
             Stack where logged:
               File "/home/xhdev/dev/miniconda3/envs/ML/lib/python3.8/runpy.py", line 194, in _run_module_as_main
                 return _run_code(code, main_globals, None,
               File "/home/xhdev/dev/miniconda3/envs/ML/lib/python3.8/runpy.py", line 87, in _run_code
                 exec(code, run_globals)
               File "/home/xhdev/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/__main__.py", line 91, in <module>
                 main()
               File "/home/xhdev/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/__main__.py", line 21, in main
                 log.describe_environment("debugpy.launcher startup environment:")
               File "/home/xhdev/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 370, in describe_environment
                 info("{0}", get_environment_description(header))
               File "/home/xhdev/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 364, in get_environment_description
                 swallow_exception("Error while enumerating installed packages.")
               File "/home/xhdev/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/common/log.py", line 215, in swallow_exception
                 _exception(format_string, *args, **kwargs)

```

**Comment by yedemon** [comment]
I seem to have the same problem. But in my case, it seems only to be a "warning" message while not affecting the debug process, still annoying. Oh, I'm just happened to use miniconda too.

**Comment by yedemon** [comment]
> I seem to have the same problem. But in my case, it seems only to be a "warning" message while not affecting the debug process, still annoying. Oh, I'm just happened to use miniconda too.

I think i found something. In one of my project, some package depends on some package called "importlib_resources 6.4.4", which doesn't have name or package. The other projects don't rely on this "Bad Guy" have no problem at all..

**Comment by yedemon** [comment]
I did some look into this crazy.. I only found it might has something related with packages installed. One of my project has those packages installed has this problem, which the others don't..

The env has the problem.
#>pip list
Package         Version
--------------- -----------
contourpy           1.1.1
cycler              0.12.1
fonttools           4.53.1
kiwisolver          1.4.5
matplotlib          3.7.5
numpy               1.24.4
opencv-python       4.10.0.84
packaging           24.1
pillow              10.4.0
pip                 24.2
pyparsing           3.1.4
python-dateutil     2.9.0.post0
setuptools          72.1.0
six                 1.16.0
wheel               0.43.0
zipp                3.20.1

The env don't have the problem.
#>pip list
Package         Version
--------------- -----------
anaconda-anon-usage     0.4.4
archspec                0.2.3
boltons                 23.0.0
Brotli                  1.0.9
certifi                 2024.6.2
cffi                    1.16.0
charset-normalizer      2.0.4
conda                   24.5.0
conda-content-trust     0.2.0
conda-libmamba-solver   24.1.0
conda-package-handling  2.3.0
conda_package_streaming 0.10.0
cryptography            42.0.5
distro                  1.9.0
frozendict              2.4.2
idna                    3.7
jsonpatch               1.33
jsonpointer             2.1
libmambapy              1.5.8
menuinst                2.1.1
packaging               23.2
pip                     24.0
platformdirs            3.10.0
pluggy                  1.0.0
pycosat                 0.6.6
pycparser               2.21
PySocks                 1.7.1
requests                2.32.2
ruamel.yaml             0.17.21
setuptools              69.5.1
tqdm                    4.66.4
truststore              0.8.0
urllib3                 2.2.2
wheel                   0.43.0
zstandard               0.22.0

Dunno if these info will mislead, I am only want to help..

**Comment by yedemon** [comment]
After a few struggle. I found if i install a package called "importlib_metadata==8.4.0" to the project which has the problem. The message "'PathDistribution' object has no attribute 'name'" disappears.. 

Try: pip install "importlib_metadata==8.4.0"

I hope this works for your situation.

Still don't know where the problem lies.

**Comment by marc22alain** [comment]
> Try: pip install "importlib_metadata==8.4.0"

I found exactly the same issue with VS Code v1.96.2 on MacOS Big Sur, and Python v3.8.5 managed with `pyenv`.
This solution worked for me too.

**Comment by rchiodo** [comment]
This should be a dupe of #1521
