### ISSUE TITLE
Specific characters in path of parent directories of file causes debugger to crash.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/debugpy#1671]
**Summary**

I've managed to break the path parsing. Specifically, including certain characters in the parent directories of the file being debugged causes the debugger to crash.

I don't know what specific characters cause this, but I'll update the report when(/if) I do.

**Reproduction**

1.	**Directory-Caused Crash**

	The undermentioned path, which contains a normal filename (`testfile.py`) but an abnormally named immediate parent directory:

	```path
	/home/RokeJulianLockhart/Documents/  [-]	`{title: "Code",	id: ""}`{.JSON5}.dir/testfile.py
	```

	...causes `ms-python.debugpy` to crash:

	<blockQuote>
	
	```log
	RokeJulianLockhart@sayw4i:~/Documents$  cd /home/RokeJulianLockhart/Documents/\ \ \[-\]\`\{title:\ \"Code\",id:\ \"\"\}\`\{.JSON5\}.dir ; /usr/bin/env /usr/bin/python3 /home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 47225 -- /home/RokeJulianLockhart/Documents/\ \ \[-\]\`\{title:\ \"Code\",id:\ \"\"\}\`\{.JSON5\}.dir/testfile.py 
	bash: cd: /home/RokeJulianLockhart/Documents/  [-]`{title: "Code",id: ""}`{.JSON5}.dir: No such file or directory
	Traceback (most recent call last):
	  File "/usr/lib64/python3.12/runpy.py", line 198, in _run_module_as_main
	    return _run_code(code, main_globals, None,
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib64/python3.12/runpy.py", line 88, in _run_code
	    exec(code, run_globals)
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
	    cli.main()
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 486, in main
	    run()
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 336, in run_file
	    runpy.run_path(target, run_name="__main__")
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
	    code, fname = _get_code_from_file(run_name, path_name)
	                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
	    with io_open_code(decoded_path) as f:
	         ^^^^^^^^^^^^^^^^^^^^^^^^^^
	FileNotFoundError: [Errno 2] No such file or directory: '/home/RokeJulianLockhart/Documents/  [-]`{title: "Code",id: ""}`{.JSON5}.dir/testfile.py'
	RokeJulianLockhart@sayw4i:~/Documents$
	```
	
	</blockQuote>

	Merely one directory in the absolute path of the file need contain such characters for the parsing to fail, as the undermentioned "Terminal" log from `ms-python.debugpy` demonstrates:

	<blockQuote>
	
	```log
	RokeJulianLockhart@sayw4i:~/Documents$  cd /home/RokeJulianLockhart/Documents/\ \ \[-\]\`\{title:\ \"Code\",id:\ \"\"\}\`\{.JSON5\}.dir/test_directory ; /usr/bin/env /usr/bin/python3 /home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 47783 -- /home/RokeJulianLockhart/Documents/\ \ \[-\]\`\{title:\ \"Code\",id:\ \"\"\}\`\{.JSON5\}.dir/test_directory/test_file.py 
	bash: cd: /home/RokeJulianLockhart/Documents/  [-]`{title: "Code",id: ""}`{.JSON5}.dir/test_directory: No such file or directory
	Traceback (most recent call last):
	  File "/usr/lib64/python3.12/runpy.py", line 198, in _run_module_as_main
	    return _run_code(code, main_globals, None,
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib64/python3.12/runpy.py", line 88, in _run_code
	    exec(code, run_globals)
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
	    cli.main()
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 486, in main
	    run()
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 336, in run_file
	    runpy.run_path(target, run_name="__main__")
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
	    code, fname = _get_code_from_file(run_name, path_name)
	                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
	    with io_open_code(decoded_path) as f:
	         ^^^^^^^^^^^^^^^^^^^^^^^^^^
	FileNotFoundError: [Errno 2] No such file or directory: '/home/RokeJulianLockhart/Documents/  [-]`{title: "Code",id: ""}`{.JSON5}.dir/test_directory/test_file.py'
	RokeJulianLockhart@sayw4i:~/Documents$
	```
	
	</blockQuote>

1.	If I put the file deep enough (like [this example](https://gitlab.com/rokejulianlockhart/sg5n9q/-/blob/5ee5d9dddd190aa306092bdbec2bdf048196801f/%20%20%5B-%5D%09%60%7Btitle:%20%22Non-Metadata%22,%09id:%20%22s1gvg2%22%7D%60%7B.JSON5%7D.dir/%20%20%5B-%5D%09%60%7Btitle:%20%22Technical%22,%09id:%20%22s20cxw%22%7D%60%7B.JSON5%7D.dir/%20%20%5B-%5D%09%60%7Btitle:%20%22Applications%22,%09id:%20%22%22%7D%60%7B.JSON5%7D.dir/%20%20%5B-%5D%09%60%7Btitle:%20%22Configurator%22,%09id:%20%22s3wrcl%22%7D%60%7B.JSON5%7D.dir/%20%20%5B-%5D%09%60%7Btitle:%20%22Code%22,%09id:%20%22%22%7D%60%7B.JSON5%7D.dir/.%20%5B-%5D%09%60%60%7Btitle:%20%22%60platform.uname()%60%7B.Py%7D%20Field%20Output%22,%09id:%20%22sgskr5%22%7D%60%60%7B.JSON5%7D.txt.Py)) it completely breaks. Enter doesn't work because the path is incorrectly escaped, so `^C` is necessary to exit the transient debug state:

	<blockQuote>
	
	```log
	RokeJulianLockhart@sayw4i:~/Software/Git/GitLab.com/RokeJulianLockhart/sg5n9q/  [-]     `{title: "Non-Metadata",        id: "s1gvg2"}`{.JSON5}.dir/  [-]        `{title: "Technical",   id: "s20cxw"}`{.JSON5}.dir/  [-]        `{title: "Applications",        id: ""}`{.JSON5}.dir/  [-] `{title: "Configurator",        id: "s3wrcl"}`{.JSON5}.dir/  [-]        `{title: "Code",        id: ""}`{.JSON5}.dir$  cd /home/RokeJulianLockhart/Software/Git/GitLab.com/RokeJulianLockhart/sg5n9q/\ \ \[-]\ `\{title\:\ \"\`\{title:\ \"Non-Metadata\",id:\ \"s1gvg2\"\}\`\{.JSON5\}.dir/\ \ \[-\]\`\{title:\ \"Technical\",id:\ \"s20cxw\"\}\`\{.JSON5\}.dir/\ \ \[-\]\`\{title:\ \"Applications\",id:\ \"\"\}\`\{.JSON5\}.dir/\ \ \[-\]\`\{title:\ \"Configurator\",id:\ \"s3wrcl\"\}\`\{.JSON5\}.dir/\ \ \[-\]\`\{title:\ \"Code\",id:\ \"\"\}\`\{.JSON5\}.dir ; /usr/bin/env /usr/bin/python3 /home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 39897 -- /home/RokeJulianLockhart/Software/Git/GitLab.com/RokeJulianLockhart/sg5n9q/\ \ \[-\]\`\{title:\ \"Non-Metadata\",id:\ \"s1gvg2\"\}\`\{.JSON5\}.dir/\ \ \[-\]\`\{title:\ \"Technical\",id:\ \"s20cxw\"\}\`\{.JSON5\}.dir/\ \ \[-\]\`\{title:\ \"Applications\",id:\ \"\"\}\`\{.JSON5\}.dir/\ \ \[-\]\`\{title:\ \"Configurator\",id:\ \"s3wrcl\"\}\`\{.JSON5\}.dir/\ \ \[-\]\`\{title:\ \"Code\",id:\ \"\"\}\`\{.JSON5\}.dir/.\ \[-\]\`\`\{title:\ \"\`platform.uname\(\)\`\{.Py\}\ Field\ Output\",id:\ \"sgskr5\"\}\`\`\{.JSON5\}.txt.Py 
	> 
	> ^C
	RokeJulianLockhart@sayw4i:~/Software/Git/GitLab.com/RokeJulianLockhart/sg5n9q/  [-]     `{title: "Non-Metadata",        id: "s1gvg2"}`{.JSON5}.dir/  [-]        `{title: "Technical",   id: "s20cxw"}`{.JSON5}.dir/  [-]        `{title: "Applications",        id: ""}`{.JSON5}.dir/  [-] `{title: "Configurator",        id: "s3wrcl"}`{.JSON5}.dir/  [-]        `{title: "Code",        id: ""}`{.JSON5}.dir$
	```
	
	</blockQuote>

	This causes https://github.com/microsoft/vscode-python-debugger/issues/361#issue-2341679070 to occur:

	> ![Screenshot_20240914_145708](https://github.com/user-attachments/assets/eb5348f0-27ad-4f8f-befa-1772c8622e37)

1.	**Debugger Functioning with Unusual Filename**

	Note that this doesn't apply to the file's name. Consider the undermentioned example:
	
	```path
	/home/RokeJulianLockhart/Documents/. [-]	``{title: "`platform.uname()`{.Py} Field Output",	id: "sgskr5"}``{.JSON5}.txt.Py
	```
	
	As the undermentioned "Terminal" log demonstrates, it functions:
	
	<blockQuote>
	
	```log
	RokeJulianLockhart@sayw4i:~/Documents$  cd /home/RokeJulianLockhart/Documents ; /usr/bin/env /usr/bin/python3 /home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024082901-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 38369 -- /home/RokeJulianLockhart/Documents/.\ \[-\]\        \`\`\{title\:\ \"\`platform.uname\(\)\`\{.Py\}\ Field\ Output\"\,\      id\:\ \"sgskr5\"\}\`\`\{.JSON5\}.txt.Py \`\`\{title:\ \"\`platform.uname\(\)\`\{.Py\}\ Field\ Output\",id:\ \"sgskr5\"\}\`\`\{.JSON5\}.txt.Py 
	for k, v in platform_uname_as_dict.items()
	system = Linux
	node = sayw4i
	release = 6.10.10-200.fc40.x86_64
	version = microsoft/vscode-python-debugger#1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:26:09 UTC 2024
	machine = x86_64
	processor = 
	RokeJulianLockhart@sayw4i:~/Documents$
	```
	
	</blockQuote>

**Environment**

1.	**Filename Character Support**

	One must be using a filesystem and OS that support such characters. I use BTRFS on Fedora 40, but anything comparable (see https://en.wikipedia.org/w/index.php?title=Filename&oldid=1245592690#Comparison_of_filename_limitations) should work.

1.	**Versions**

	1.	**Code**
	
		1.	```sh
			rpm -q 'code' 'code-insiders'
			```
			
		1.	> ```log
			> code-1.93.1-1726079369.el8.x86_64
			> code-insiders-1.94.0-1726207949.el8.x86_64
			> ```

	1.	**Debugger**

		https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/debugpy/2024.11.2024082901/vspackage?targetPlatform=linux-x64 (from https://github.com/microsoft/vscode-python-debugger/releases/download/v2024.11.2024082901/extension.vsixmanifest).

**Miscellaneous**

Potentially related to https://github.com/microsoft/vscode-python-debugger/issues/233#issue-2152958262, although I doubt it, because `/home/RokeJulianLockhart/Documents/Text File.txt.py` works.

<!-- `path`, per https://community.splunk.com/t5/Getting-Data-In/I-see-splunk-has-some-quot-path-quot-files-in-windows-app-bin/m-p/11657/highlight/true#M669 -->

**Comment by rchiodo** [comment]
Looking at the other issue, we seem to translate tab characters into an escaped tab. I would guess that's the root cause of this issue.

**Comment by debonte** [comment]
I'm not seeing it escaped, but rather stripped out. It happens before the path is given to debugpy. Not sure if this is a vscode-python-debugger issue, a vscode issue, or what.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/debugpy/issues/1671#issuecomment-2353436644

Indeed, it's the tabs. Working back from the right, I removed one character per test, and ascertained that <code>[]`{:"",</code> works as a path:

```log
RokeJulianLockhart@sayw4i:~/Documents/[]`{:"",  : ""}`{.}$  cd /home/RokeJulianLockhart/Documents/\[\]\`\{:\"\", ; /usr/bin/env /usr/bin/python3 /home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024092501-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 37961 -- /home/RokeJulianLockhart/Documents/\[\]\`\{:\"\",/test_file.py 
test
```

...but <code>[]`{:"",	</code> doesn't:

```log
RokeJulianLockhart@sayw4i:~/Documents/[]`{:"",  : ""}`{.}$  cd /home/RokeJulianLockhart/Documents/\[\]\`\{:\"\", ; /usr/bin/env /usr/bin/python3 /home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024092501-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 37483 -- /home/RokeJulianLockhart/Documents/\[\]\`\{:\"\",/test_file.py 
bash: cd: /home/RokeJulianLockhart/Documents/[]`{:"",: No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024092501-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024092501-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024092501-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024092501-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 309, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024092501-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 278, in _get_code_from_file
    with io_open_code(decoded_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/RokeJulianLockhart/Documents/[]`{:"",/test_file.py'
```

**Comment by gramster** [comment]
Yes, the quote function at https://github.com/microsoft/vscode/blob/393f929eff78295f740f2c801728d9238d8c6ec7/src/vs/workbench/contrib/debug/node/terminals.ts#L163 strips out the tab.
