### ISSUE TITLE
Support gevent with frame eval mode

### ISSUE THREAD

**Issue by dalmago** [microsoft/debugpy#189]
## Environment data

- PTVSD version: 4.3.0
- OS and version: Windows 7 Pro
- Python version: 3.6.1
- Using VS Code

## Actual behavior

The code unexpectedly exits when I set the GEVENT_SUPPORT environment variable to True. Getting the following error:

```
Unhandled exception in thread started by SystemError: ..\Objects\codeobject.c:851: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_pydevd_frame_eval\pydevd_frame_evaluator.pyx", line 187, in _pydevd_frame_eval.pydevd_frame_evaluator.get_func_code_info
Fatal Python error: GC object already tracked

...

Thread 0x000031b8 (most recent call first):
  File "C:\Python 3.6\lib\threading.py", line 295 in wait
  File "C:\Python 3.6\lib\threading.py", line 551 in wait
  File "C:\Python 3.6\lib\site-packages\ptvsd\attach_server.py", line 42 in wait_for_attach
  File "mytest_ptvsd.py", line 12 in myfunc
  File "mytest_ptvsd.py", line 21 in <module>
```

The error happens when I press the "Start Debugging" button on VS Code.
Enabling gevent support because I want to debug some code that uses socketio.

## Expected  behavior

This used to work fine with PTVSD 4.2.10.

## Steps to reproduce:
```python
import os

os.environ["GEVENT_SUPPORT"] = 'True'

import ptvsd

DEBUG_PORT = 5678

def myfunc():
    ptvsd.enable_attach(('localhost', DEBUG_PORT))
    print("Please attach debugger to port ", DEBUG_PORT)
    ptvsd.wait_for_attach()  # blocks execution until debugger is attached

    print("Debugger attached")

    print("testing 1 2 3")
    x = 0
    print(x)

if __name__ == "__main__":
    myfunc()

```

**Comment by pirumpi** [comment]
It would be nice to add a simple example on adding the enable_attach flag to gevent, those post don't provide any real help 👎

**Comment by fabioz** [comment]
@pirumpi

The enable attach should work in gevent provided you have a `GEVENT_SUPPORT=1` environment variable set (this issue is unrelated to that).

Note that the latest gevent broke the debugger, so, you must pin to a previous version (the last supported version is `20.9.0`) to be able to use `debugpy` along with `gevent`. See: https://github.com/microsoft/debugpy/issues/515
