### ISSUE TITLE
Short path handling is broken on Python 2.7

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#192]
In dbg_adapter_refactor branch, this happens as soon as you import ptvsd - so e.g. in a test run, as soon as it starts running, even before test discovery:
```
pydev debugger: critical: unable to get real case for file. Details:
filename: C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_file_utils.py
drive: C:\
parts: ['git', 'longpa~1', 'ptvsd', 'src', 'ptvsd', '_vendored', 'pydevd', 'pydevd_file_utils.py']
(please create a ticket in the tracker to address this).

  File "C:\git\LONGPA~1\ptvsd\setup.py", line 31, in <module>
    import ptvsd
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\__init__.py", line 39, in <module>
    from ptvsd.server.attach_server import (
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\server\__init__.py", line 7, in <module>
    import ptvsd._vendored.force_pydevd
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\force_pydevd.py", line 37, in <module>
    'pydevd',
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\__init__.py", line 123, in preimport
    import_module(name)
  File "C:\Python\2.7-64\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\pydevd\pydevd.py", line 27, in <module>
    from _pydevd_bundle.pydevd_filtering import FilesFiltering
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_filtering.py", line 7, in <module>
    import pydevd_file_utils
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 216, in <module>
    _get_path_with_real_case(__file__)
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 210, in _get_path_with_real_case
    traceback.print_stack()
Traceback (most recent call last):
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 202, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "C:\git\LONGPA~1\ptvsd\src\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 169, in _resolve_listing
    resolve_lowercase, resolved))
IOError: Unable to find: longpa~1 in C:\git
error: could not delete '_pydevd_bundle\pydevd_cython.pyd': Access is denied
```
(I've added `traceback.print_stack()` in pydevd code to get the full trace)

To repro:
```
mkdir "long path with spaces"
chdir longpa~1
git clone https://github.com/microsoft/ptvsd/
chdir ptvsd
tox --develop -e py27
```
It seems that this has to do in part with case mismatch between "longpa~1" and "LONGPA~1", although I am not sure which comes whence. If you allow the test suite to run, there will be multiple assertion failures as well, and in all of them it is because a path didn't match due to case mismatch at that point.

**Comment by judej** [comment]
Python 2.7 will no longer be supported after January 2022; we will not be supporting debugging on 2.7.
