### ISSUE TITLE
Python warnings in debugger code

### ISSUE THREAD

**Issue by pkolbus** [microsoft/debugpy#351]
## Environment data

-   VS Code version: 1.47.3
-   Extension version (available under the Extensions sidebar): 2020.7.96456
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a
-   Relevant/affected Python packages and their versions: n/a
-   Relevant/affected Python-related VS Code extensions and their versions: n/a
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

No deprecation warnings.

**Note**: the Python 3.9 release notes encourage developers to check for `DeprecationWarning`, as many deprecated APIs are being removed in 3.9 and 3.10. See https://docs.python.org/3.9/whatsnew/3.9.html for details.

## Actual behaviour

Terminal (Python Debug Console) contains a DeprecationWarning:
```
cd /home/kolbus/my-project ; env /usr/bin/python3.8 /home/kolbus/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/launcher 37295 -- /home/kolbus/.local/bin/pylint_runner 
/home/kolbus/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/common/compat.py:186: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  arg_names, args_name, kwargs_name, arg_defaults = inspect.getargspec(f)
```

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a folder containing a simple Python file (even `print("Hello World")` is sufficient)
2. From the Run view, click "create a launch.json file"
3. Create a configuration and add `PYTHONWARNINGS=default`, i.e.:
```
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env": {"PYTHONWARNINGS": "default"}
        }
    ]
```
4. Launch the debugger session.

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Error 2020-07-29 07:45:18: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/kolbus/projects/test-project/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/kolbus/projects/test-project/.vscode/settings.json')
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:657:25)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async v.readText (/home/kolbus/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:1:571666)
	at async p.doesFileNeedToBeFixed (/home/kolbus/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:48:932592)
	at async /home/kolbus/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:48:931719
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/kolbus/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:48:931665)
	at async p.updateTestSettings (/home/kolbus/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:48:931292)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> pyenv root
> pyenv root
> pyenv root
Starting Pylance language server.
Python interpreter path: /usr/bin/python3.8
Error 2020-07-29 07:45:19: Attempted to download with skipDownload true.
> pyenv root
> conda --version
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
```

</p>
</details>

**Comment by int19h** [comment]
There are more warnings past this one, especially on shutdown, so I'm going to expand this item to cover the entirety of that cleanup.
