### ISSUE TITLE
listen throws "RuntimeError: timed out waiting for adapter to connect"

### ISSUE THREAD

**Issue by nyue** [microsoft/debugpy#456]
## Environment data

- debugpy version: XXX (run `import debugpy; print(debugpy.__version__)` if uncertain)
1.1.0
- OS and version: XXX
Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): XXX
2.7.14 (Python from the Cinema4D application, called c4dpy.exe)
- Using VS Code or Visual Studio:
VSCode 1.42.1
## Actual behavior

>>> import debugpy
>>> debugpy.listen(5678)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\UserPython\Python27\site-packages\debugpy\__init__.py", line 113, in listen
    return api.listen(address)
  File "d:\UserPython\Python27\site-packages\debugpy\server\api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "d:\UserPython\Python27\site-packages\debugpy\server\api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "d:\UserPython\Python27\site-packages\debugpy\server\api.py", line 232, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect

## Expected  behavior

>>> import debugpy
>>> debugpy.listen(5678)
('127.0.0.1', 5678)

## Steps to reproduce:
1. XXX

**Comment by dougransom** [comment]
I experience the same thing, python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)] on win32

Python is hosted in another executable.  VS Code 1.51.1 can never attach, though i think the problem is in debugby.





`
Traceback (most recent call last):
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 218, in listen
    sock, _ = endpoints_listener.accept()
  File "C:\Python38-32\Lib\socket.py", line 292, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\natlinkutilsbj.py", line 1225, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\natlinkutilsbj.py", line 672, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 856, in resultsCallback
    self.callRuleResultsFunctions(seqsAndRules, fullResults)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 881, in callRuleResultsFunctions
    self.callIfExists( 'gotResults_'+ruleName, (ruleWords, fullResults) )
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 379, in callIfExists
    return func(*argList)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\_control.py", line 313, in gotResults_trace
    actions.debugActions(traceNum)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\actions.py", line 850, in debugActions
    connect_debugger()
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\actions.py", line 823, in connect_debugger
    debugpy.listen(port) 
  File "C:\Python38-32\lib\site-packages\debugpy\__init__.py", line 113, in listen
    return api.listen(address)
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 232, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect
`

**Comment by dougransom** [comment]
Here are the logs generated with the problem manifests.

**Comment by dougransom** [comment]
here are the logs for `    debugpy.listen(port) 
`
[debugpy.pydevd.18888.log](https://github.com/microsoft/debugpy/files/5580426/debugpy.pydevd.18888.log)
[debugpy.server-18888.log](https://github.com/microsoft/debugpy/files/5580427/debugpy.server-18888.log)

**Comment by int19h** [comment]
From the log, this is why the server failed to spawn the debug adapter:
```
I+00000.016: debugpy.listen() spawning adapter: [
                 "C:\\Program Files (x86)\\Nuance\\NaturallySpeaking15\\Program\\natspeak.exe",
                 "C:\\Python38-32\\lib\\site-packages\\debugpy\\adapter",
                 "--for-server",
                 "49455",
                 "--host",
                 "127.0.0.1",
                 "--port",
                 "7474",
                 "--server-access-token",
                 "7b1c0e347d7d7a08339d0ef5d480b862853e4aa19f8ce3a339c93a8fc5cda39d",
                 "--log-dir",
                 "C:\\Users\\dougr\\OneDrive\\doug\\dication_toolbox\\unimacro\\logs"
             ]
```
It looks like it's hosted Python, rather than standalone? debugpy will use `sys.executable` by default to spawn its helper processes, assuming that it's a valid Python interpreter; but in hosted scenarios, that's not the case. In those, you need to point it at some suitable interpreter, like so:
```py
debugpy.configure(python=r"C:\Python\python.exe")
debugpy.listen(...)
```

**Comment by dougransom** [comment]
@int19 That fixed my problem, it will be so helpful!  Thanks.  I wonder if that was @nyue's problem too.

**Comment by int19h** [comment]
It seems likely, since the original bug mentions that this is Python hosted in Cinema4D. @nyue, if the above steps don't fix the problem for you, please re-open.

**Comment by carlos-villavicencio-adsk** [comment]
Fixed when debugging Shotgrid with Maya as well.
