### ISSUE TITLE
Error message for embedded python adapter timeout

### ISSUE THREAD

**Issue by dougransom** [microsoft/debugpy#480]
## Environment data
debugpy version: 
1.1.0
OS and version:
Windows 10
Python 3.8 32 bit,  embedded in a windows app.  
VSCode 1.42.1

## Actual behavior
`mport debugpy
debugpy.listen(5678)
('127.0.0.1', 5678)`

A traceback that doesn't help solve the problem:
`Traceback (most recent call last):
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 218, in listen
    sock, _ = endpoints_listener.accept()
  File "C:\Python38-32\Lib\socket.py", line 292, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\natlinkutilsbj.py", line 1225, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\natlinkutilsbj.py", line 672, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 856, in resultsCallback
    self.callRuleResultsFunctions(seqsAndRules, fullResults)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 881, in callRuleResultsFunctions
    self.callIfExists( 'gotResults_'+ruleName, (ruleWords, fullResults) )
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 379, in callIfExists
    return func(*argList)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\_control.py", line 313, in gotResults_trace
    actions.debugActions(traceNum)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\actions.py", line 850, in debugActions
    connect_debugger()
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\actions.py", line 823, in connect_debugger
    debugpy.listen(port) 
  File "C:\Python38-32\lib\site-packages\debugpy\__init__.py", line 113, in listen
    return api.listen(address)
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 232, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect`

## Expected  behavior

An exception thrown indicating I should specify the python executable  like `debugpy.configure(python="C:\Python\python.exe")`

## Steps to reproduce:
1. XXX

**Comment by int19h** [comment]
The problem is that we don't know that's why it's failing. On the server side, it takes `sys.executable` and uses it to spawn a new process. If that fails immediately, the error will be reported, but in this scenario, it is a valid binary, so it actually runs - it's just that it doesn't do what we expect a regular Python interpreter to do. There are other ways in which this can break, too - e.g. if there's some .pth that's printing output. 

So, we need to find some way to detect that it's really caused by the executable not being a valid interpreter. The only way I can think of doing so is by checking the name, but then we'd have to account for all the various possibilities ("python_d", "python3.8" etc), as well as alternative implementations like PyPy. It would also need some escape hatch to allow interpreters that we don't detect correctly, just in case - perhaps this could kick in if `debugpy.configure()` is used, so for those unusual interpreters, one would have to do something like `debugpy.configure(python=sys.executable)` to override the error.

**Comment by dougransom** [comment]
Maybe a hint then?  Like the command line creating the adapter?

**Comment by judej** [comment]
Moving this issue to discussion as an enhancement request for comments and upvotes.
