### ISSUE TITLE
Debugging fails to start when Visual Studio Code Remote automatically forwards ports from a GitHub Codespace

### ISSUE THREAD

**Issue by jarrodldavis** [microsoft/debugpy#506]
## Environment data

- debugpy version: Not sure, whatever is included in the [VS Code Python extension][vsc-python], v2020.12.424452561 (run `import debugpy; print(debugpy.__version__)` if uncertain) [this didn't work, I get `ModuleNotFoundError: No module named 'debugpy'`]
- OS and version: macOS 11.1 Big Sur, remoting into a GitHub Codespace running Debian 10 (buster) using [this dev container][devcon]
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.6
- Using VS Code or Visual Studio: Visual Studio Code

## Actual behavior

Debugging fails with connection refused errors (similar to #84) when ports are automatically forward from a Codespace (default behavior of Visual Studio Code).

## Expected  behavior

Debugging a Django app starts fine even when ports are (automatically) forwarded, or Visual Studio Code doesn't automatically forward ports important for Python debugging.

## Steps to reproduce:
1. Create a GitHub Codespace for a Django app using the [Python 3 & Postgres Development Container][devcon]
2. Once the Codespace is finished initializing, try to start debugging
3. Observe that some ports are automatically forwarded by Visual Studio Code
4. Debugging fails with a `Connection refused` error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vscode/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher/__main__.py", line 95, in <module>
    main()
  File "/home/vscode/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher/__main__.py", line 51, in main
    launcher.connect(host, port)
  File "/home/vscode/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher/../../debugpy/launcher/__init__.py", line 34, in connect
    sock.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
```

I was able to work around this issue by disabling automatic port forwarding (setting `remote.autoForwardPorts` to `false`) and reloading Visual Studio Code.

[vsc-python]: https://github.com/microsoft/vscode-python
[devcon]: https://github.com/microsoft/vscode-dev-containers/tree/v0.154.1/containers/python-3-postgres

**Comment by int19h** [comment]
This is sort of expected when VSCode remote server forwards all ports, since debugpy uses a bunch of them for local connections.

It appears that there's now a (as yet unstable) VSCode API that extensions can use to tell the port forwarder to ignore some addresses: https://github.com/microsoft/vscode/issues/11561; the Jupyter extension is already using it, so the core Python extension might have to start doing that, as well.

For launch, this should be fairly easy, since only the adapter process opens listener ports, and the extension spawns it directly, so it knows its PID - so `PortAttributesProvider` can just return ignore for all ports for that PID.

For attach, it's trickier because the adapter gets spawned by the debuggee in that scenario, and the extension doesn't know its PID or port numbers. It looks like the port provider API has an optional command line argument - if it's reliable enough, it could be used to filter anything matching `debugpy.adapter`. If not, we might need to devise some alternative communication mechanism from the adapter to the extension, that it can use to communicate its PID *before* it opens any ports.

@karthiknadig, what do you think?

**Comment by karthiknadig** [comment]
In the attach case since it is not really spawned by a process under VS Code process tree will the ports be forwarded at all?

**Comment by int19h** [comment]
@jarrodldavis Does this still reproduce for you? Debugging a web app in a Codespace seems to be working fine for me.

**Comment by int19h** [comment]
Please re-open if this issue is still relevant.

**Comment by AndreasLuckert** [comment]
Hello, maybe [this solution posted on StackOverFlow](https://stackoverflow.com/a/73280867/12298276) helps you. It seems to be a similar problem.
