### ISSUE TITLE
Error when attaching by process to python running in Maya

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#52]
```
pydev debugger: Unable to find real location for: C:\Program Files\Autodesk\Maya2017\bin\python27.zip\ntpath.py
pydev debugger: Unable to find real location for: C:\Program Files\Autodesk\Maya2017\bin\python27.zip\genericpath.py
pydev debugger: Unable to find real location for: C:\Program Files\Autodesk\Maya2017\bin\python27.zip\ctypes\__init__.py
pydev debugger: Unable to find real location for: C:\Program Files\Autodesk\Maya2017\bin\python27.zip\threading.py
pydev debugger: Unable to find real location for: C:\Program Files\Autodesk\Maya2017\bin\python27.zip\SocketServer.py
pydev debugger: Unable to find real location for: C:\Program Files\Autodesk\Maya2017\bin\python27.zip\traceback.py
pydev debugger: Unable to find real location for: C:\Program Files\Autodesk\Maya2017\bin\python27.zip\linecache.py
Traceback (most recent call last):
  File "c:\Users\v-rokowa\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\server\attach_pid_injected.py", line 74, in attach
    ptvsd.attach((options.host, options.port))
  File "c:\Users\v-rokowa\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\__init__.py", line 109, in attach
    return api.attach(address, log_dir)
  File "c:\Users\v-rokowa\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\server\api.py", line 75, in debug
    raise log.exception("{0}() failed:", func.__name__, level="info")
AssertionError: Paths passed to _NormPaths must be str. Found: C:/Users/v-rokowa/Documents/maya/2017/prefs/scripts\<string> (<type 'unicode'>)
pydev debugger: Unable to find real location for: C:\Program Files\Autodesk\Maya2017\bin\python27.zip\string.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\v-rokowa\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\server\attach_pid_injected.py", line 86, in attach
    raise log.exception()
AssertionError: Paths passed to _NormPaths must be str. Found: C:/Users/v-rokowa/Documents/maya/2017/prefs/scripts\<string> (<type 'unicode'>)
```

**Comment by int19h** [comment]
Can you add the logs, so that we can see the stack inside pydevd?

**Comment by fabioz** [comment]
There are 2 things there:

1. the warnings about `Unable to find real location` -- this is probably correct (they probably only distribute the .pycs).

2. the exception `Paths passed to _NormPaths must be str`. I'm a bit puzzled by how that happened.
It's really strange that it got a `<string>` being unicode... I thought that maybe passing `unicode` to compile on Python 2.7 could generate that, but I haven't been able to do it here (so, I don't really know how Maya got that).

i.e.:
```
>>> c = compile('def method(): pass', u'<string>', 'exec')
>>> exec(c)
>>> method.func_code.co_filename
'<string>'
>>> type(method.func_code.co_filename)
<type 'str'>
```

@karthiknadig, is this from some user? If so, is it possible to add him to the discussion?

**Comment by fabioz** [comment]
Is it possible to run the snippet below inside of Maya and provide the output?

```
import sys
frame = sys._getframe()
attrs = ['co_filename', 'co_name', 'co_firstlineno']
while frame:
    print('---- frame info ----')
    for attr in attrs:
        value = getattr(frame.f_code, attr)
        print('%s: %s (%s)' % (attr, value, type(value)))
    frame = frame.f_back
```

**Comment by fabioz** [comment]
The issue seems to be that `sys.path` has a unicode entry and it's taking a path where the filename is joined with `sys.path` -- https://github.com/microsoft/debugpy/blob/v1.0.0b3/src/debugpy/_vendored/pydevd/pydevd_file_utils.py#L488

I'm working on a fix for this.
