### ISSUE TITLE
Remote debugger won't detach when running uvicorn app with --reload

### ISSUE THREAD

**Issue by gionapaolini** [microsoft/debugpy#696]
## Environment data

- debugpy version: 1.4.1 
- OS and version: Windows 10
- Python version: python:3.9.6-alpine3.13 (in docker)
- Using VS Code or Visual Studio: VS Code

## Actual behavior
Debugging works fine, but when I'm finished and I click on the detach button the remote debugger won't detach.

## Expected  behavior

Remote debugger should stop and close

## Steps to reproduce:
1. Create a very simple fastapi app called app.py
```
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}
```
2. Run it with debugpy and with uvicorn and --reload option (I run it in a docker container it so that I can then attach remotely, and make sure to expore ports 5678 and 80)
```
python -u -m debugpy --listen 0.0.0.0:5678 -m uvicorn --reload --host 0.0.0.0 --port 80 app:app
```
3. Attach to it with the following launch.json config:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Remote debugging",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "...",              -> make sure to map source files correctly
                    "remoteRoot": "..." 
                }
            ]
        }
    ]
}
```
Importing debugpy inside the app itself works, but I was wondering if I can make it work without this workaround.

**Comment by int19h** [comment]
This appears to be a VSCode issue when handling process trees.

What happens here is that there are two process at play - the parent process that has the monitoring / reloading logic, and the child process that actually runs user code. When you click Disconnect, VSCode sends the "disconnect" request to the parent process, and this completes successfully, ending that debug session. However, the child process is still running, and it is *not* disconnected from.

This one would be a minor issue by itself - you'd only need to click Disconnect once more to disconnect from the child process, as well. The problem is that VSCode seems to be confused by the fact that the parent session has ended, but the child session is still running. If Developer Tools are enabled, clicking on Disconnect the second time produces this error in the console:

```
 ERR cannot find session: Error: cannot find session
	at b.getSession (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:37097)
	at b.$acceptDebugSessionTerminated (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:34016)
	at h._doInvokeHandler (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
	at h._invokeHandler (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
	at h._receiveRequest (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11159)
	at h._receiveOneMessage (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
	at c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
	at d.fire (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
	at d.fire (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at r._receiveMessage (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
	at c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
	at d.fire (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at v.acceptChunk (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
	at c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
	at Socket.w (c:\Users\pminaev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

And from debugpy perspective, it simply doesn't receive the second "disconnect" request at all, and thus continues running.
