### ISSUE TITLE
can not  debug pytest in integratedTerminal

### ISSUE THREAD

**Issue by kevinwang89** [microsoft/debugpy#702]
## Environment data
Version: 

-   VS Code version: 1.59.1 (user setup)
-   Extension version (available under the Extensions sidebar): v2021.8.1147840270
-   OS and version: Windows_NT x64 10.0.19042
-   Python version (& distribution if applicable, e.g. Anaconda): python3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

 debug pytest open debug terminal and hit breakpoint

## Actual behaviour

python debug file works fine in integrated terminal.

but pytest debug output in debug console : failed to load _ssl module

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. set launch configuration
```
  {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
```
2.  debug simple pytest example
```

def test_empty():
    logging.info('empty test')
```
3. debug output in debug console and failed , not in integrated Terminal

### python test log
```
python c:\Users\kevin\.vscode\extensions\ms-python.python-2021.8.1147840270\pythonFiles\testing_tools\run_adapter.py discover pytest -- --rootdir e:\myCode\python\pytest -s --cache-clear
Error: TypeError: Cannot read property 'testsuites' of null
Error: TypeError: Cannot read property 'testsuites' of null
Error: TypeError: Cannot read property 'testsuites' of null
```

![Screenshot 2021-08-23 202427](https://user-images.githubusercontent.com/33874210/130446619-b79fff60-3af7-4fa9-ad8d-acdf685e4e0e.png)

**Comment by int19h** [comment]
This looks like Conda activation issue. Can you show the contents of your terminal?

**Comment by kevinwang89** [comment]
@int19h I can run the test from test explorer, but debug failed to hit break point, below is the debug console error info
```
Traceback (most recent call last):
  File "D:\miniconda3\envs\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda3\envs\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\kevin\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\kevin\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\kevin\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "D:\miniconda3\envs\py39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\miniconda3\envs\py39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\miniconda3\envs\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\kevin\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\testlauncher.py", line 51, in <module>
    run(cwd, testRunner, args)
  File "c:\Users\kevin\.vscode\extensions\ms-python.python-2021.8.1159798656\pythonFiles\testlauncher.py", line 39, in run
    pytest.main(args)
  File "D:\miniconda3\envs\py39\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "D:\miniconda3\envs\py39\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "D:\miniconda3\envs\py39\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "D:\miniconda3\envs\py39\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "D:\miniconda3\envs\py39\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "D:\miniconda3\envs\py39\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "D:\miniconda3\envs\py39\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "D:\miniconda3\envs\py39\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\miniconda3\envs\py39\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "D:\miniconda3\envs\py39\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "D:\miniconda3\envs\py39\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "D:\miniconda3\envs\py39\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "D:\miniconda3\envs\py39\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "D:\miniconda3\envs\py39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\miniconda3\envs\py39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\miniconda3\envs\py39\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "D:\miniconda3\envs\py39\lib\site-packages\anyio\__init__.py", line 88, in <module>
    from ._core._sockets import (
  File "D:\miniconda3\envs\py39\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "D:\miniconda3\envs\py39\lib\site-packages\anyio\_core\_sockets.py", line 2, in <module>
    import ssl
  File "D:\miniconda3\envs\py39\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: The specified module could not be found.

```

**Comment by int19h** [comment]
The error itself is clear, but if it's really caused by conda activation issues, the relevant information will be in the terminal (which is a separate pane from debug output). I'm particularly interested in any commands submitted to the shell prompts, and the resulting output.

**Comment by kevinwang89** [comment]
problem is debug does not open any terminal, so I can not check the commands and the output, error info simply goes to the debug console

**Comment by int19h** [comment]
That's very unusual, and more like the behavior of `"console": "internalConsole"` than `"integratedTerminal"`. Can you double-check that this is indeed the configuration being run?

Also, can you please add this to your config:
```json5
"logToFile": true,
```
then do it one more time, and then share  `C:\Users\kevin\.vscode\extensions\ms-python.python-2021.8.1159798656\debugpy*.log` for that run.

**Comment by kevinwang89** [comment]
I added `<logToFile>` in debug config
project now has only one debug config,  and it works fine in python file debugging.  and logs are saved in extension folder.
when it comes with pytest debug, debug fails, and there is no logs files in extension folder. 
I tried reinstall vs code,  no use.

**Comment by int19h** [comment]
Running unit tests in VSC uses a separate debug config - it should be the one that has `"request": "test"` in your launch.json. That one is where "logToFile" and other specifics should go into. If you don't have it, you should see the template for it in Add Configuration.

**Comment by kevinwang89** [comment]
@int19h  it's my launch config mistake, change to `"request": "test"` it works now. thank you !
