### ISSUE TITLE
Editor margin breakpoints not triggering

### ISSUE THREAD

**Issue by ross-weir** [microsoft/debugpy#760]
Hopefully this is the right place for this.

Breakpoints set in the editor margin aren't triggered unless a `breakpoint()` statement was previously used.

## Environment data

-   VS Code version: 1.61.1 (system setup)
-   Extension version (available under the Extensions sidebar): v2021.11.1313923388-dev
-   OS and version: Windows_NT x64 10.0.19042
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Relevant/affected Python packages and their versions: any
-   Relevant/affected Python-related VS Code extensions and their versions: any
-   Value of the `python.languageServer` setting: `Pylance`

## Expected behaviour

Breakpoints set in the editor margin should be triggered without needing a `breakpoint()` statement to be triggered first.

## Actual behaviour

Editor margin breakpoints are not triggered unless a `breakpoint()` statement has been triggered.

## Steps to reproduce:

Example repository including `launch.json`: https://github.com/ross-weir/vscode_breakpoint_issue

1. Set a breakpoint using the editor margin anywhere in the `if main` block

<img width="248" alt="vsc1" src="https://user-images.githubusercontent.com/29697678/137583461-314640e5-0591-40db-8f3c-8ff51438786c.PNG">

2. Debug the python module (using f5)
3. Observe output in terminal but no breakpoints triggered
4. Add a breakpoint statement anywhere before a editor margin breakpoint:

<img width="240" alt="vsc2" src="https://user-images.githubusercontent.com/29697678/137583514-88d8f62e-ffaf-4c44-9c1a-caef8292c625.PNG">

5. Debug the python module
6. The program breaks at the line after the `breakpoint()` statement, line 3 in my example
7. Press f5 to continue running the program
8. The program will resume and this time it will break on the editor margin breakpoint on line 5

![vsc-bp-example](https://user-images.githubusercontent.com/29697678/137584104-f64a96c4-b785-4c29-afc4-abac52a9ec15.gif)

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayed'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayed'
User belongs to experiment group 'pythonRememberDebugConfig'
Info 2021-10-16 21:13:39: Cached data exists KeyPrefix=Cache_Method_Output_h.addKeyToStorage-Args="global"-Arg-Separator-"WORKSPACE_FOLDER_INTERPRETER_PATH_D:\\DEVELOPMENT\\LEARNING\\VSCODE_BREAKPOINTS_ISSUE"-Arg-Separator-undefined
Python interpreter path: ~\AppData\Local\pypoetry\Cache\virtualenvs\vscode-breakpoints-issue-vN-JjK-U-py3.10\Scripts\python.exe
Starting Pylance language server.
> conda --version
```

</p>
</details>

**Comment by fabioz** [comment]
I can see an error in the extension that is responsible for setting up the tracing:

```
Error attaching debugger tracing
Traceback (most recent call last):
  File "c:\Users\Ross\.vscode\extensions\ms-python.python-2021.11.1347845452-dev\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_tracing.py", line 357, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
Error attaching debugger tracing
Traceback (most recent call last):
  File "c:\Users\Ross\.vscode\extensions\ms-python.python-2021.11.1347845452-dev\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_tracing.py", line 357, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
```

So, tracing isn't being properly setup.

An initial workaround here is setting an environment variable such that:

`PYDEVD_LOAD_NATIVE_LIB=0`

Now, this is a workaround so that the native lib isn't loaded. 

I think the real problem is that you're using `Python 3.10.0alpha2`. CPython changes a lot among alpha releases, so, the debugger targets only the final release (i.e.: `3.10.0 final`), so, please upgrade the version you're using to a stable version to get the debugger working properly.
