### ISSUE TITLE
Problems with python in VSC, eg. not working logs and pathlib and importlib.util

### ISSUE THREAD

**Issue by ManPython** [microsoft/debugpy#764]
## Environment data

- debugpy version:1.5.0
- OS and version: W10
- Python version (& distribution if applicable, e.g. Anaconda): Venv for P3.8 
- Using VS Code or Visual Studio:

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

- **Django: (3, 2, 6, 'final', 0)**

## Actual behavior
1. Errors
```
Traceback (most recent call last):
  File "E:\Python38\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "E:\Python38\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "E:\p38-venv\lib\site-packages\django\utils\log.py", line 195, in format
    return super().format(record)
  File "E:\Python38\lib\logging\__init__.py", line 667, in format
    s = self.formatMessage(record)
  File "E:\Python38\lib\logging\__init__.py", line 636, in formatMessage
    return self._style.format(record)
  File "E:\Python38\lib\logging\__init__.py", line 438, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'server_time'
Call stack:
  File "e:\Microsoft\.vscode\extensions\ms-python.python-2021.10.1336267007\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 1054, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "E:\Python38\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "E:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Python38\lib\socketserver.py", line 652, in process_request_thread
    self.handle_error(request, client_address)
  File "E:\p38-venv\lib\site-packages\django\core\servers\basehttp.py", line 75, in handle_error
    logger.info("- Broken pipe from %s\n", client_address)
Message: '- Broken pipe from %s\n'
Arguments: (('127.0.0.1', 63627),)
```
2. Not importing files
`[Errno 2] No such file or directory: 'mydir\\\\test.py'`
3. No logs from 
```
            "env": {
               "PTVSD_LOG_DIR":"C:\\Logs",
               "PYDEVD_DEBUG":"True",
               "PYDEVD_DEBUG_FILE":"C:\\Logs\\pydevd.log"
```

## Expected  behavior

1. Run normal Django app without problems.
2.  Well work app like on windows terminal where no problems, no errors, no problem with import like in point 2.**
3. Some logs on `"C:\\Logs",` to check what is going on.. 

## Steps to reproduce:
1. When runing in VSC Django as
```
.vscode\extensions\ms-python.python-2021.10.1336267007'; & 'e:\p38-venv\Scripts\python.exe'
'e:\Microsoft\.vscode\extensions\ms-python.python-2021.10.1336267007\pythonFiles\lib\python\debugpy\launcher' '63604' '--' 
'E:\django\manage.py' 'runserver' '127.0.0.1:8000' '--traceback' '-v' '3' 
```
2. Have errors like 1, and problem with import as `[Errno 2] No such file or directory: 'mydir\\\\test.py'`
**3. When ruining on windows terminal `django>python manage.py runserver` then all ok..** 

_Hi, I'm back again.. that mind's hard problems that can solve by own ;p_

**Comment by ManPython** [comment]
Hard to say it's bug when working in win terminal.. 
Also I just updated VSC today. I'm not actuall with debugpy, still not log erros.

```
        {   "name": "p38-venv Django Debugpy",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "python": "E:\\p38-venv\\Scripts\\python.exe",
            "program": "${workspaceRoot}\\django\\manage.py",
            "console": "integratedTerminal",
            "args": ["runserver", "127.0.0.1:8000", "--traceback", "-v", "3", "--log-to"],
            "django": true,
            "subProcess": true,
            "justMyCode":  false,
            "env": {
            "logToFile": true,
               "PTVSD_LOG_DIR":"C:\\Logs",
               "PYDEVD_DEBUG":"True",
               "PYDEVD_DEBUG_FILE":"C:\\Logs\\pydevd.log"
            },
            "logToFile": true,
            //"envFile": "${workspaceRoot}/path/to/virtualenv",
            //"envFile": "${workspaceRoot}\\",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging",
                "ShowReturnValue",
          
```

**Comment by int19h** [comment]
If you use "logToFile", it should put the logs into `e:\Microsoft\.vscode\extensions\ms-python.python-...` - take a look there. And I don't think we respect `PTVSD_LOG_DIR` anymore; it's been `DEBUGPY_LOG_DIR` for a while.

Regarding the first error - it might be triggered by debugger calling `repr()` on the object.

**Comment by ManPython** [comment]
> And I don't think we respect PTVSD_LOG_DIR anymore; it's been DEBUGPY_LOG_DIR for a while.

Ahh see... : )
Clear. Solved. Can be closed. Thx again.
Working with
```
Version: 1.62.1
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by ManPython** [comment]
Also not working in finall well coz VSC and Debugpy changing path outside the `E:\PYTHON\Python38` to `C:\\Users\\user\\AppData\\Roaming\\Python\\Python38\\`
```
Exception has occurred: FileNotFoundError
[WinError 3] The system cannot find the path specified : 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python38\\site-packages'
  File "E:\PYTHON\Python38\Lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
  File "E:\PYTHON\Python38\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\PYTHON\Python38\Lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
```

**Comment by ManPython** [comment]
Oh.. also its issue around python 38
https://github.com/gcovr/gcovr/issues/365#issuecomment-700218039

**Comment by int19h** [comment]
The error stack above is from the standard [runpy](https://docs.python.org/3/library/runpy.html) module trying to resolve the path - we shouldn't be doing anything there, just passing things through from command line.

If you do `import runpy; runpy.run_path(r"E:\django\manage.py")` directly (e.g. from Python's own REPL), does it give you the same error?

**Comment by ManPython** [comment]
> If you do `import runpy; runpy.run_path(r"E:\django\manage.py")` directly (e.g. from Python's own REPL), does it give you the same error?

No. And nothing around path to reffering path specified : 'C: only E:

**Comment by ManPython** [comment]
But I found case where if breakpoints in VSC is turned off then working, and when turn on `Raise Exeptions` then not working.

**Comment by ManPython** [comment]
@int19h this issue is critical !
https://github.com/microsoft/debugpy/issues/764#issuecomment-965825104
The path must be changed, cant be called something that not existing.

I adding simple project to test. Regarding this post https://github.com/microsoft/debugpy/issues/764#issuecomment-965904421 then other case with error:
`app_dirs must not be set when loaders is defined.`
But it's basic example, hard to say that is something wrong done here, cor working in CMD outside VSC.

[django329.zip](https://github.com/microsoft/debugpy/files/7809750/django329.zip)

**Comment by ManPython** [comment]
I tried to mklink /J to my python dir but the `Exception has occurred: FileNotFoundError [WinError 2]` 
that no file can't be found as
 `Python38-venv\\Scripts\\python38.zip`

Is this case can be related with Python38`-`venv in env name as "-" ?

**Comment by int19h** [comment]
To clarify, when you're testing it without the debugger, are you using the venv as well?

The dash in directory name should not be a problem. It's not a special character in any sense.

**Comment by ManPython** [comment]
> To clarify, when you're testing it without the debugger, are you using the venv as well?

Yes. And spyder worki ok and other (pyscripter).

I wokring with this from 1hour to find problem. I build other venvs, instaled other pythons. I found problem. Need some time to clear logs and show here.

**Comment by ManPython** [comment]
Why `site.getusersitepackages():`  calling `C:\`? 
```
                 sys.real_prefix: <missing>
                 site.getsitepackages(): E:\Python38venv
                                         E:\Python38venv\lib\site-packages(E:\Python38venv\Lib\site-packages)
                 site.getusersitepackages(): C:\Users\ManPython\AppData\Roaming\Python\Python38\site-packages
```

And here:

```
# Does a path exist?
# This is false for dangling symbolic links on systems that support them.
def exists(path):
    """Test whether a path exists.  Returns False for broken symbolic links"""
    try:
        os.stat(path)
    except (OSError, ValueError):
        return False
    return True

```

as pat `E:\Python38venv\Python38.zip` - in case no .zip in venv.. 

The funny situation, that about .zip in base simple project not have this issue.

**Comment by ManPython** [comment]
To be clear, there never was any Python here:
`site.getusersitepackages(): C:\Users\ManPython\AppData\Roaming\Python\Python38\site-packages`
Coz using something like portable version python (no installation, just addin path by `setx path` etc. as required).

**Comment by fabioz** [comment]
@ManPython are you still reproducing this?

```
Exception has occurred: FileNotFoundError
[WinError 3] The system cannot find the path specified : 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python38\\site-packages'
  File "E:\PYTHON\Python38\Lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
  File "E:\PYTHON\Python38\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\PYTHON\Python38\Lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
```

Can you temporarily change `E:\PYTHON\Python38\Lib\runpy.py` to add the code below (at line 194 right before the line `return _run_code(code, main_globals, None,` and then provide the output of making that run?

```
    print('---- CALLER STACK -----')
    import traceback
    traceback.print_stack()
    print('-------- CODE ---------')
    import dis
    dis.dis(code)
    print('--------- END ---------')
```

**Comment by ManPython** [comment]
> @ManPython are you still reproducing this?

Still.. 

> Can you temporarily change `E:\PYTHON\Python38\Lib\runpy.py` to add the code below (at line 194 right before the line `return _run_code(code, main_globals, None,`) and then provide the output of making that run?

I do this change, but VSC can't run app, just working long time (the progress bar still moving from left to right under run). 
I should wait longer time? More than 30mins? : )
I try without breakpoints chexkbox under debuger VSC, but this same.

**Comment by ManPython** [comment]
The `C:\\Users\\user\\AppData\\Roaming\\Python\\Python38\\` looks starting in line 34 of ntpath.py
```
def _get_bothseps(path):
    if isinstance(path, bytes):
        return b'\\/'
    else:
        return '\\/'
```

- have addon in VSC that disclose the varaibles next to functions etc

**Comment by ManPython** [comment]
In 646 can change:
ntpath.py
```
        try:
            path = 'E:\\PYTHON\\Python38\\Lib\\site-packages'
            #path = _getfinalpathname(path)
            initial_winerror = 0
``
but then this error again
https://github.com/microsoft/debugpy/issues/764#issuecomment-1005728357

Looks like error in venv for p38? Or what?

**Comment by ManPython** [comment]
https://github.com/microsoft/debugpy/issues/390

**Comment by ManPython** [comment]
Also I copier python37.zip and renamed to python38.zip and no errors, but Django app is not started in finally and in terminal not  started as normaly, more like not reaction (probably buy wrong version zip).
Why is required the .zip and why I don't have this?

**Comment by ManPython** [comment]
After download python38.zip from embed 
https://www.python.org/downloads/release/python-380/

```
Exception has occurred: FileNotFoundError
[WinError 2] project\\django\\runpy.py' #why here?

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

 File "E:\Python38\Lib\genericpath.py", line 19, in exists
    os.stat(path)
  File "E:\Python38\Lib\runpy.py", line 85, in _run_code
    __package__ = pkg_name,
  File "E:\Python38\Lib\runpy.py", line 192, in _run_module_as_main
    if alter_argv:
``

**Comment by ManPython** [comment]
I installed python310 and created venv.. and this same error as upper.

**Comment by ManPython** [comment]
Can be related more with this issue as vscode-python due usage of breakpoints?
https://github.com/Microsoft/vscode-python/issues/18455

**Comment by ManPython** [comment]
Still not understanding why this path.. 
https://github.com/microsoft/debugpy/issues/764#issuecomment-1024631614

```
SKIP set tracing of frame: e:\Microsoft\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py - main
SKIP set tracing of frame: e:\Microsoft\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\__main__.py - <module>
File not traced (not in project): E:\PYTHON\Python38\lib\ntpath.py
Suspending all threads except: <_MainThread(MainThread, started 9468)>
PyDB.do_wait_suspend
name: realpath (line: 647)
 file: E:\PYTHON\Python38\lib\ntpath.py
 event: exception
 arg: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'The specified file could not be found.'), <traceback object at 0x000001719F54F1C0>)
 step: CMD_STEP_INTO (original step: <Unknown: -1>)
 thread: <_MainThread(MainThread, started 9468)>, thread id: pid_13532_id_1587500902624, id(thread): 1587500902624
  Stack: E:\PYTHON\Python38\lib\ntpath.py, realpath, 647
  Stack: e:\Microsoft\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\common\log.py, report_paths, 319
  Stack: e:\Microsoft\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\common\log.py, describe_environment, 331
  Stack: e:\Microsoft\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py, run_file, 282
  Stack: e:\Microsoft\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py, main, 444
  Stack: e:\Microsoft\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\__main__.py, <module>, 45
  Stack: E:\PYTHON\Python38\lib\runpy.py, _run_code, 87
  Stack: E:\PYTHON\Python38\lib\runpy.py, _run_module_as_main, 194
Sending suspend notification
```

**Comment by ManPython** [comment]
@fabioz 
It was possibe to do trace on new dbugpy
https://github.com/microsoft/debugpy/issues/764#issuecomment-1024160851
[trace.txt](https://github.com/microsoft/debugpy/files/8146618/trace.txt)

But the venv is style like system not venv.
