### ISSUE TITLE
Django debug in wsl always pending

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/debugpy#769]
## Environment data

-   VS Code version: 1.52.1
-   Extension version (available under the Extensions sidebar): 2020.12.424452561
-   OS and version: Windows 1909
-   Python version (& distribution if applicable, e.g. Anaconda): 2.7.17
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: Django 1.8.12
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance 2020.12.2
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour
Debug can start and pause in my breakpoint

## Actual behaviour
Just pending like this screenshot and never move on.

![image](https://user-images.githubusercontent.com/17985592/103405338-b1c8cc80-4b91-11eb-9e07-77f08120c139.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run code . in wsl project folder
2. Configure launch.json to run debug
3. Click run  debug icon in top left .

launch.json file:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "127.0.0.1:5000"
            ],
            "console": "integratedTerminal",
            "django": true
        }
    ]
}
```

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'AlwaysDisplayTestExplorer - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - experiment'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonSendEntireLineToREPL'
> conda --version
> pyenv root
> python3.7 ~/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-12-31 17:53:54: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-18.04/home/jeffrey/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/jeffrey/.config/Code/User/settings.json')
	at _handleError (/home/jeffrey/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:769:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/home/jeffrey/.vscode-server/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:9:262389)
	at async p.doesFileNeedToBeFixed (/home/jeffrey/.vscode-server/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:59:489303)
	at async /home/jeffrey/.vscode-server/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:59:488430
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/jeffrey/.vscode-server/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:59:488376)
	at async p.updateTestSettings (/home/jeffrey/.vscode-server/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:59:488003)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Python interpreter path: ./.venv/bin/python2.7
Starting Pylance language server.
> conda --version
```

</p>
</details>

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with additional information. thanks
