### ISSUE TITLE
TypeError: 'NoneType' obj on df.pivot() in debugger

### ISSUE THREAD

**Issue by YSaxon** [microsoft/debugpy#835]
Issue Type: <b>Bug</b>

Using [the example code from the df.pivot docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html):

```
import pandas as pd
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
                           'two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})

df.pivot(index='foo', columns='bar', values='baz')
```

If I paste that into a new python file and debug it, I get the following:
![Screen Shot 2022-02-04 at 1 42 05 PM](https://user-images.githubusercontent.com/11711101/152585580-962da36e-6928-416a-aed1-8ab5a191a265.png)

```
Traceback (most recent call last):
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/numpy/core/getlimits.py", line 649, in __init__
    self.dtype = numeric.dtype(int_type)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ysaxon/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/ysaxon/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/ysaxon/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ysaxon/[redacted]/temp_pandas_test.py", line 8, in <module>
    df.pivot(index='foo', columns='bar', values='baz')
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/frame.py", line 7876, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/reshape/pivot.py", line 520, in pivot
    return indexed.unstack(columns_listlike)
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/series.py", line 4154, in unstack
    return unstack(self, level, fill_value)
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/reshape/reshape.py", line 491, in unstack
    unstacker = _Unstacker(
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/reshape/reshape.py", line 133, in __init__
    if num_cells > np.iinfo(np.int32).max:
  File "/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/numpy/core/getlimits.py", line 651, in __init__
    self.dtype = numeric.dtype(type(int_type))
TypeError: 'NoneType' object is not callable

```

And if I instead run it in the Debug Console, I get the following:

```
Traceback (most recent call last):
  File "[/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/numpy/core/getlimits.py]()", line 649, in __init__
    self.dtype = numeric.dtype(int_type)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/frame.py]()", line 7876, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "[/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/reshape/pivot.py]()", line 520, in pivot
    return indexed.unstack(columns_listlike)
  File "[/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/series.py]()", line 4154, in unstack
    return unstack(self, level, fill_value)
  File "[/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/reshape/reshape.py]()", line 491, in unstack
    unstacker = _Unstacker(
  File "[/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pandas/core/reshape/reshape.py]()", line 133, in __init__
    if num_cells > np.iinfo(np.int32).max:
  File "[/Users/ysaxon/.pyenv/versions/3.10.2/lib/python3.10/site-packages/numpy/core/getlimits.py]()", line 651, in __init__
    self.dtype = numeric.dtype(type(int_type))
TypeError: 'NoneType' object is not callable
```

I'm not certain that the bug is in vscode, but I suspect it is, as the code runs fine on the command line, REPL, or when clicking the run (without debugging) button in vscode.

NumPy: v1.22.1 
Pandas: v1.4.0
Extension version: 2022.0.1786462952
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 1bf17335-f719-451e-83ea-c3fbb78fa7d4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsclayoutctrc:30425945
vsrem710cf:30416617

```

</details>

**Comment by YSaxon** [comment]
@brettcannon
I don't believe I have conda installed
I'm using Python 3.10.2 installed by pyenv (which was itself installed by homebrew)

**Comment by YSaxon** [comment]
I think this might be related to https://github.com/microsoft/debugpy/issues/801

**Comment by gramster** [comment]
Yes, seems like a dup of #801

**Comment by NEXT-JP** [comment]
> Yes, seems like a dup of #801

Hey, that's my issue! Just found this one (#835) in a google search while encountering this "'NoneType' obj on df.pivot()" problem in my code.
