### ISSUE TITLE
RuntimeError: logging has already begun

### ISSUE THREAD

**Issue by tekumara** [microsoft/debugpy#836]
```python
import debugpy
import pytest


def main() -> None:
    print("Attach vscode to debugger on port 62888")
    debugpy.listen(62888)
    debugpy.log_to('logs/')
    debugpy.wait_for_client()
    pytest.main()


if __name__ == "__main__":
    main()
```

When run:
```
Attach vscode to debugger on port 62888
Traceback (most recent call last):
  File "/Users/tekumara/code/hypothesis-debug-vscode/.venv/bin/hdebug", line 33, in <module>
    sys.exit(load_entry_point('hdebug', 'console_scripts', 'hdebug')())
  File "/Users/tekumara/code/hypothesis-debug-vscode/hdebug/main.py", line 8, in main
    debugpy.log_to('logs/')
  File "/Users/tekumara/code/hypothesis-debug-vscode/.venv/lib/python3.9/site-packages/debugpy/__init__.py", line 51, in log_to
    return api.log_to(path)
  File "/Users/tekumara/code/hypothesis-debug-vscode/.venv/lib/python3.9/site-packages/debugpy/server/api.py", line 72, in log_to
    raise RuntimeError("logging has already begun")
RuntimeError: logging has already begun
```

**Comment by tekumara** [comment]
To resolve call `log_to` before `listen`, eg:

```python
debugpy.log_to('logs/')
debugpy.listen(62888)
debugpy.wait_for_client()
```
